### ISSUE TITLE
 Log Button not available in 1.3.3

### ISSUE THREAD

**Issue by elsa-arroyo** [codecentric/spring-boot-admin#170] opened 2016-03-14 18:26 UTC
Hello, I have a similar isuue than marco79cgn (issue #128).

Spring boot clients and servers are running 1.3.x
All clients registrer successfully in the admin, I see all functionality working, except the Log button.

Just as Marco, I am able to see my logfile in a url like
"http://localhost:9999/api/applications/ea12a7b7/logfile" (I am running my spring-boot-admin-server on port 9999 because I am using 8080 on another application).

I have been tracking my /configprops and I noticed that I am missing "environmentMvcEndpoint" and "logfileMvcEndpoint" objects in my JSON. 

I have tried to enable all endpoints in my properties file, but no luck.  Any ideas what could be wrong or missing?

**Comment by elsa-arroyo** [comment] 2016-03-14 18:36
Just discovered that we are also setting server.port and management.port, so I could reproduce Marco's bug. Is there any workaround or fix for this?

Thank you very much for your help.

**Comment by joshiste** [comment] 2016-03-14 21:02
duplicate of #165.
This has been fixed in the master branch, but not released yet.

**Closed by joshiste** 2016-03-14 21:02 UTC
