### ISSUE TITLE
Memory: Non heap fails with: Request failed with status code 404 when using adoptopenjdk openj9 

### ISSUE THREAD

**Issue by heka-pulsen** [codecentric/spring-boot-admin#1305] opened 2019-11-21 12:16 UTC
When using adoptopenjdk openj9 the graph for Memory: Non heap fails with 'Request failed with status code 404'. Using developer tools in Chrome I see that this request fails with status 404:
http://localhost:8091/instances/099a8b85dfe1/actuator/metrics/jvm.memory.used?tag=area:nonheap,id:Metaspace

If remove ',id:Metaspace' from the url I get this response:
{"name":"jvm.memory.used","description":"The amount of used memory","baseUnit":"bytes","measurements":[{"statistic":"VALUE","value":7.1701168E7}],"availableTags":[{"tag":"id","values":["JIT code cache","class storage","miscellaneous non-heap storage","JIT data cache"]}]}
There is no 'Metaspace' value for the tag 'id' which is why the request fails...

I'm using version 2.1.6 of Spring Boot Admin and version jdk8u212-b03 of AdoptOpenJDK.

**Comment by joshiste** [comment] 2019-11-27 06:17
This is a duplicate of #1235 and has been fixed for the 2.2.x branch.

**Closed by joshiste** 2019-11-27 06:17 UTC
Labels: duplicate
