### ISSUE TITLE
Client registration with http basic auth broken

### ISSUE THREAD

**Issue by rfelgent** [codecentric/spring-boot-admin#292] opened 2016-10-04 19:50 UTC
Hi,

I think the RestTemplateBuilder usage in class 'SpringBootAdminClientAutoConfiguration' does not work the way it is used there. Exactly the code 'builder.basicAuthorization(admin.getUsername(), admin.getPassword());' is broken, as a new instance of RestTemplateBuilder is created/returned underneath and therefore not used afterwards in 'return new ApplicationRegistrator(builder.build(), admin, client);'. The BasicAuthorizationInterceptor(username, password) is never applied.

Currently, my Spring Boot applications are unable to register on a SBAP that is protected via http basic auth.

**Comment by rfelgent** [comment] 2016-10-04 19:55
I think the fluent api pattern is not well implemented in RestTemplateBuilder, as always a new instance is returned instead of "this" (the current one).

**Comment by joshiste** [comment] 2016-10-04 19:55
I guess you are not using the latest 1.4.2?

**Comment by joshiste** [comment] 2016-10-04 19:56
This has been fixed with #247...

**Comment by rfelgent** [comment] 2016-10-04 19:56
Hi @joshiste ,

thx for the fast response. I am using SBAP 1.4.1

**Comment by joshiste** [comment] 2016-10-04 19:56
duplicate of #247

**Comment by rfelgent** [comment] 2016-10-04 19:57
Ok, i will try 1.4.2. Sorry for the duplicate. Isn't it a good idea to update the documentation?

**Closed by joshiste** 2016-10-04 19:56 UTC
Labels: duplicate

**Comment by joshiste** [comment] 2016-10-04 19:58
The linked docs in README.md are up to date.
