### ISSUE TITLE
spring-boot-admin-client 1.4.2 no longer registers with spring-boot-admin

### ISSUE THREAD

**Issue by nedenom** [codecentric/spring-boot-admin#291] opened 2016-10-03 10:39 UTC
After upgrading both spring-boot-admin and admin-client to 1.4.2, the client no longer registers with spring-boot-admin server. When downgrading client to 1.4.1 again, it does in fact register again. I did no changes except changing version in pom.xml when testing this.

With 1.4.2 I see nothing in the logs about application trying to register itself - or anything else about spring-boot-admin, so it may seem that autoconfiguration is no longer working - or has anything major changed with 1.4.2?

**Comment by joshiste** [comment] 2016-10-03 12:35
I guess you are using spring cloud config? Then this is a duplicate of #277.

**Comment by nedenom** [comment] 2016-10-03 12:44
Actually not using Spring Cloud Config (no spring-cloud-config-*.jar on the classpath), but using other Spring Cloud dependencies such as Netflix.

**Comment by nedenom** [comment] 2016-10-03 12:54
Tested 1.4.3-SNAPSHOT and registration works on this version, so fix was probably applicable either way. Thanks.

**Comment by joshiste** [comment] 2016-10-03 13:40
duplicate pf #277

**Closed by joshiste** 2016-10-03 13:40 UTC
Labels: waiting-for-feedback
