### ISSUE TITLE
Is admin server compatible with spring-cloud Brixton.RC2 ?

### ISSUE THREAD

**Issue by ouaibsky** [codecentric/spring-boot-admin#191] opened 2016-05-09 13:13 UTC
Hi

I embed admin server into an existing µService that has dependency itself  on spring cloud Brixton.RC2
And I got a couple of exception, mainly I think because admin server is using sping-cloud netflix as well (in order to add some check around eureka.)

I Look at boot-admin dep and found that:
>  <spring-cloud.version>Brixton.BUILD-SNAPSHOT</spring-cloud.version>

Is it possible to release something without snapshot ?

I used admin-server 1.3.2 and I got this error:
```log
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cloud.netflix.zuul.filters.route.SimpleHostRoutingFilter]: Factory method 'simpleHostRoutingFilter' threw exception; nested exception is java.lang.NoSuchMethodError: org.springframework.cloud.netflix.zuul.filters.route.SimpleHostRoutingFilter.<init>(Lorg/springframework/cloud/netflix/zuul/filters/ProxyRequestHelper;)V
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
	... 47 common frames omitted
Caused by: java.lang.NoSuchMethodError: org.springframework.cloud.netflix.zuul.filters.route.SimpleHostRoutingFilter.<init>(Lorg/springframework/cloud/netflix/zuul/filters/ProxyRequestHelper;)V
	at de.codecentric.boot.admin.config.RevereseZuulProxyConfiguration.simpleHostRoutingFilter(RevereseZuulProxyConfiguration.java:71)
	at de.codecentric.boot.admin.config.RevereseZuulProxyConfiguration$$EnhancerBySpringCGLIB$$745fd8c.CGLIB$simpleHostRoutingFilter$1(<generated>)
	at de.codecentric.boot.admin.config.RevereseZuulProxyConfiguration$$EnhancerBySpringCGLIB$$745fd8c$$FastClassBySpringCGLIB$$c77d091e.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:355)
	at de.codecentric.boot.admin.config.RevereseZuulProxyConfiguration$$EnhancerBySpringCGLIB$$745fd8c.simpleHostRoutingFilter(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
	... 48 common frames omitted
```
If need I can provide classpath.
Christophe

**Comment by ouaibsky** [comment] 2016-05-09 13:36
same erro with SNAPSHOT:  
```
file:/E:/opt/jdk1.8.0_31-windows-x64/jre/lib/charsets.jar
 file:/E:/opt/jdk1.8.0_31-windows-x64/jre/lib/deploy.jar
 file:/E:/opt/jdk1.8.0_31-windows-x64/jre/lib/javaws.jar
 file:/E:/opt/jdk1.8.0_31-windows-x64/jre/lib/jce.jar
 file:/E:/opt/jdk1.8.0_31-windows-x64/jre/lib/jfr.jar
 file:/E:/opt/jdk1.8.0_31-windows-x64/jre/lib/jfxswt.jar
 file:/E:/opt/jdk1.8.0_31-windows-x64/jre/lib/jsse.jar
 file:/E:/opt/jdk1.8.0_31-windows-x64/jre/lib/management-agent.jar
 file:/E:/opt/jdk1.8.0_31-windows-x64/jre/lib/plugin.jar
 file:/E:/opt/jdk1.8.0_31-windows-x64/jre/lib/resources.jar
 file:/E:/opt/jdk1.8.0_31-windows-x64/jre/lib/rt.jar
 file:/E:/opt/jdk1.8.0_31-windows-x64/jre/lib/ext/access-bridge-64.jar
 file:/E:/opt/jdk1.8.0_31-windows-x64/jre/lib/ext/cldrdata.jar
 file:/E:/opt/jdk1.8.0_31-windows-x64/jre/lib/ext/dnsns.jar
 file:/E:/opt/jdk1.8.0_31-windows-x64/jre/lib/ext/jaccess.jar
 file:/E:/opt/jdk1.8.0_31-windows-x64/jre/lib/ext/jfxrt.jar
 file:/E:/opt/jdk1.8.0_31-windows-x64/jre/lib/ext/localedata.jar
 file:/E:/opt/jdk1.8.0_31-windows-x64/jre/lib/ext/nashorn.jar
 file:/E:/opt/jdk1.8.0_31-windows-x64/jre/lib/ext/sunec.jar
 file:/E:/opt/jdk1.8.0_31-windows-x64/jre/lib/ext/sunjce_provider.jar
 file:/E:/opt/jdk1.8.0_31-windows-x64/jre/lib/ext/sunmscapi.jar
 file:/E:/opt/jdk1.8.0_31-windows-x64/jre/lib/ext/sunpkcs11.jar
 file:/E:/opt/jdk1.8.0_31-windows-x64/jre/lib/ext/zipfs.jar
 file:/E:/workspace/onyx/onyx-admin/target/classes/
 file:/D:/maven-local-repo/commons-configuration/commons-configuration/1.8/commons-configuration-1.8.jar
 file:/D:/maven-local-repo/commons-lang/commons-lang/2.6/commons-lang-2.6.jar
 file:/D:/maven-local-repo/de/codecentric/spring-boot-admin-server/1.3.2/spring-boot-admin-server-1.3.2.jar
 file:/D:/maven-local-repo/com/fasterxml/jackson/core/jackson-databind/2.6.6/jackson-databind-2.6.6.jar
 file:/D:/maven-local-repo/com/netflix/zuul/zuul-core/1.1.0/zuul-core-1.1.0.jar
 file:/D:/maven-local-repo/commons-io/commons-io/2.4/commons-io-2.4.jar
 file:/D:/maven-local-repo/com/netflix/archaius/archaius-core/0.7.4/archaius-core-0.7.4.jar
 file:/D:/maven-local-repo/com/google/code/findbugs/jsr305/3.0.1/jsr305-3.0.1.jar
 file:/D:/maven-local-repo/com/netflix/servo/servo-core/0.10.1/servo-core-0.10.1.jar
 file:/D:/maven-local-repo/com/netflix/servo/servo-internal/0.10.1/servo-internal-0.10.1.jar
 file:/D:/maven-local-repo/com/netflix/netflix-commons/netflix-commons-util/0.1.1/netflix-commons-util-0.1.1.jar
 file:/D:/maven-local-repo/org/springframework/cloud/spring-cloud-netflix-core/1.1.0.BUILD-SNAPSHOT/spring-cloud-netflix-core-1.1.0.BUILD-20160506.201018-396.jar
 file:/D:/maven-local-repo/org/springframework/boot/spring-boot/1.3.4.RELEASE/spring-boot-1.3.4.RELEASE.jar
 file:/D:/maven-local-repo/org/springframework/boot/spring-boot-autoconfigure/1.3.4.RELEASE/spring-boot-autoconfigure-1.3.4.RELEASE.jar
 file:/D:/maven-local-repo/org/springframework/cloud/spring-cloud-commons/1.1.0.BUILD-SNAPSHOT/spring-cloud-commons-1.1.0.BUILD-20160506.180957-151.jar
 file:/D:/maven-local-repo/org/springframework/security/spring-security-crypto/4.0.4.RELEASE/spring-security-crypto-4.0.4.RELEASE.jar
 file:/D:/maven-local-repo/org/apache/httpcomponents/httpclient/4.5.2/httpclient-4.5.2.jar
 file:/D:/maven-local-repo/org/apache/httpcomponents/httpcore/4.4.4/httpcore-4.4.4.jar
 file:/D:/maven-local-repo/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
 file:/D:/maven-local-repo/de/codecentric/spring-boot-admin-server-ui/1.3.2/spring-boot-admin-server-ui-1.3.2.jar
 file:/D:/maven-local-repo/org/apache/geronimo/specs/geronimo-jms_1.1_spec/1.1/geronimo-jms_1.1_spec-1.1.jar
 file:/D:/maven-local-repo/org/aspectj/aspectjweaver/1.8.9/aspectjweaver-1.8.9.jar
 file:/D:/maven-local-repo/org/ff4j/ff4j-aop/1.4/ff4j-aop-1.4.jar
 file:/D:/maven-local-repo/org/slf4j/slf4j-api/1.7.21/slf4j-api-1.7.21.jar
 file:/D:/maven-local-repo/org/springframework/spring-context/4.2.6.RELEASE/spring-context-4.2.6.RELEASE.jar
 file:/D:/maven-local-repo/org/springframework/spring-expression/4.2.6.RELEASE/spring-expression-4.2.6.RELEASE.jar
 file:/D:/maven-local-repo/org/ff4j/ff4j-core/1.4/ff4j-core-1.4.jar
 file:/D:/maven-local-repo/org/ff4j/ff4j-security-spring/1.4/ff4j-security-spring-1.4.jar
 file:/D:/maven-local-repo/org/springframework/security/spring-security-core/4.0.4.RELEASE/spring-security-core-4.0.4.RELEASE.jar
 file:/D:/maven-local-repo/org/springframework/security/spring-security-web/4.0.4.RELEASE/spring-security-web-4.0.4.RELEASE.jar
 file:/D:/maven-local-repo/org/springframework/security/spring-security-config/4.0.4.RELEASE/spring-security-config-4.0.4.RELEASE.jar
 file:/D:/maven-local-repo/org/ff4j/ff4j-utils-json/1.4/ff4j-utils-json-1.4.jar
 file:/D:/maven-local-repo/org/fusesource/stompjms/stompjms-client/1.19/stompjms-client-1.19.jar
 file:/D:/maven-local-repo/org/fusesource/hawtdispatch/hawtdispatch-transport/1.20/hawtdispatch-transport-1.20.jar
 file:/D:/maven-local-repo/org/fusesource/hawtdispatch/hawtdispatch/1.20/hawtdispatch-1.20.jar
 file:/D:/maven-local-repo/org/fusesource/hawtbuf/hawtbuf/1.11/hawtbuf-1.11.jar
 file:/D:/maven-local-repo/org/springframework/spring-aop/4.2.6.RELEASE/spring-aop-4.2.6.RELEASE.jar
 file:/D:/maven-local-repo/aopalliance/aopalliance/1.0/aopalliance-1.0.jar
 file:/D:/maven-local-repo/org/springframework/spring-beans/4.2.6.RELEASE/spring-beans-4.2.6.RELEASE.jar
 file:/D:/maven-local-repo/org/springframework/spring-core/4.2.6.RELEASE/spring-core-4.2.6.RELEASE.jar
 file:/D:/maven-local-repo/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
 file:/D:/maven-local-repo/org/springframework/boot/spring-boot-starter-mustache/1.3.3.RELEASE/spring-boot-starter-mustache-1.3.3.RELEASE.jar
 file:/D:/maven-local-repo/org/springframework/boot/spring-boot-starter/1.3.4.RELEASE/spring-boot-starter-1.3.4.RELEASE.jar
 file:/D:/maven-local-repo/org/yaml/snakeyaml/1.16/snakeyaml-1.16.jar
 file:/D:/maven-local-repo/com/samskivert/jmustache/1.11/jmustache-1.11.jar
 file:/D:/maven-local-repo/org/springframework/cloud/spring-cloud-starter-eureka/1.1.0.BUILD-SNAPSHOT/spring-cloud-starter-eureka-1.1.0.BUILD-20160509.110322-379.jar
 file:/D:/maven-local-repo/org/springframework/cloud/spring-cloud-starter/1.1.0.BUILD-SNAPSHOT/spring-cloud-starter-1.1.0.BUILD-20160506.181002-151.jar
 file:/D:/maven-local-repo/org/springframework/cloud/spring-cloud-context/1.1.0.BUILD-SNAPSHOT/spring-cloud-context-1.1.0.BUILD-20160506.180933-152.jar
 file:/D:/maven-local-repo/org/springframework/security/spring-security-rsa/1.0.1.RELEASE/spring-security-rsa-1.0.1.RELEASE.jar
 file:/D:/maven-local-repo/org/bouncycastle/bcpkix-jdk15on/1.47/bcpkix-jdk15on-1.47.jar
 file:/D:/maven-local-repo/org/bouncycastle/bcprov-jdk15on/1.47/bcprov-jdk15on-1.47.jar
 file:/D:/maven-local-repo/org/springframework/cloud/spring-cloud-netflix-eureka-client/1.1.0.BUILD-SNAPSHOT/spring-cloud-netflix-eureka-client-1.1.0.BUILD-20160509.110103-162.jar
 file:/D:/maven-local-repo/com/netflix/eureka/eureka-client/1.4.6/eureka-client-1.4.6.jar
 file:/D:/maven-local-repo/org/codehaus/jettison/jettison/1.3.7/jettison-1.3.7.jar
 file:/D:/maven-local-repo/stax/stax-api/1.0.1/stax-api-1.0.1.jar
 file:/D:/maven-local-repo/com/netflix/netflix-commons/netflix-eventbus/0.3.0/netflix-eventbus-0.3.0.jar
 file:/D:/maven-local-repo/javax/ws/rs/jsr311-api/1.1.1/jsr311-api-1.1.1.jar
 file:/D:/maven-local-repo/com/sun/jersey/jersey-core/1.19.1/jersey-core-1.19.1.jar
 file:/D:/maven-local-repo/com/sun/jersey/jersey-client/1.19.1/jersey-client-1.19.1.jar
 file:/D:/maven-local-repo/com/sun/jersey/contribs/jersey-apache-client4/1.19.1/jersey-apache-client4-1.19.1.jar
 file:/D:/maven-local-repo/com/google/inject/guice/4.0/guice-4.0.jar
 file:/D:/maven-local-repo/com/netflix/governator/governator-api/1.12.10/governator-api-1.12.10.jar
 file:/D:/maven-local-repo/com/netflix/eureka/eureka-core/1.4.6/eureka-core-1.4.6.jar
 file:/D:/maven-local-repo/com/amazonaws/aws-java-sdk-core/1.10.30/aws-java-sdk-core-1.10.30.jar
 file:/D:/maven-local-repo/com/amazonaws/aws-java-sdk-ec2/1.10.30/aws-java-sdk-ec2-1.10.30.jar
 file:/D:/maven-local-repo/com/amazonaws/aws-java-sdk-autoscaling/1.9.3/aws-java-sdk-autoscaling-1.9.3.jar
 file:/D:/maven-local-repo/com/amazonaws/aws-java-sdk-sts/1.9.3/aws-java-sdk-sts-1.9.3.jar
 file:/D:/maven-local-repo/com/amazonaws/aws-java-sdk-route53/1.9.3/aws-java-sdk-route53-1.9.3.jar
 file:/D:/maven-local-repo/com/netflix/governator/governator/1.12.10/governator-1.12.10.jar
 file:/D:/maven-local-repo/com/netflix/governator/governator-core/1.12.10/governator-core-1.12.10.jar
 file:/D:/maven-local-repo/org/ow2/asm/asm/5.0.4/asm-5.0.4.jar
 file:/D:/maven-local-repo/org/codehaus/woodstox/woodstox-core-asl/4.4.1/woodstox-core-asl-4.4.1.jar
 file:/D:/maven-local-repo/javax/xml/stream/stax-api/1.0-2/stax-api-1.0-2.jar
 file:/D:/maven-local-repo/org/springframework/cloud/spring-cloud-starter-archaius/1.1.0.BUILD-SNAPSHOT/spring-cloud-starter-archaius-1.1.0.BUILD-20160506.201246-158.jar
 file:/D:/maven-local-repo/org/springframework/cloud/spring-cloud-starter-ribbon/1.1.0.BUILD-SNAPSHOT/spring-cloud-starter-ribbon-1.1.0.BUILD-20160506.201254-377.jar
 file:/D:/maven-local-repo/com/netflix/ribbon/ribbon/2.1.5/ribbon-2.1.5.jar
 file:/D:/maven-local-repo/com/netflix/ribbon/ribbon-transport/2.1.5/ribbon-transport-2.1.5.jar
 file:/D:/maven-local-repo/io/reactivex/rxnetty-contexts/0.4.9/rxnetty-contexts-0.4.9.jar
 file:/D:/maven-local-repo/io/reactivex/rxnetty-servo/0.4.9/rxnetty-servo-0.4.9.jar
 file:/D:/maven-local-repo/io/reactivex/rxnetty/0.4.9/rxnetty-0.4.9.jar
 file:/D:/maven-local-repo/io/netty/netty-codec-http/4.0.27.Final/netty-codec-http-4.0.27.Final.jar
 file:/D:/maven-local-repo/io/netty/netty-codec/4.0.27.Final/netty-codec-4.0.27.Final.jar
 file:/D:/maven-local-repo/io/netty/netty-handler/4.0.27.Final/netty-handler-4.0.27.Final.jar
 file:/D:/maven-local-repo/io/netty/netty-transport-native-epoll/4.0.27.Final/netty-transport-native-epoll-4.0.27.Final.jar
 file:/D:/maven-local-repo/io/netty/netty-common/4.0.27.Final/netty-common-4.0.27.Final.jar
 file:/D:/maven-local-repo/io/netty/netty-buffer/4.0.27.Final/netty-buffer-4.0.27.Final.jar
 file:/D:/maven-local-repo/io/netty/netty-transport/4.0.27.Final/netty-transport-4.0.27.Final.jar
 file:/D:/maven-local-repo/com/netflix/ribbon/ribbon-core/2.1.5/ribbon-core-2.1.5.jar
 file:/D:/maven-local-repo/com/netflix/ribbon/ribbon-httpclient/2.1.5/ribbon-httpclient-2.1.5.jar
 file:/D:/maven-local-repo/commons-collections/commons-collections/3.2.2/commons-collections-3.2.2.jar
 file:/D:/maven-local-repo/com/netflix/ribbon/ribbon-loadbalancer/2.1.5/ribbon-loadbalancer-2.1.5.jar
 file:/D:/maven-local-repo/com/netflix/netflix-commons/netflix-statistics/0.1.1/netflix-statistics-0.1.1.jar
 file:/D:/maven-local-repo/io/reactivex/rxjava/1.0.14/rxjava-1.0.14.jar
 file:/D:/maven-local-repo/com/netflix/ribbon/ribbon-eureka/2.1.5/ribbon-eureka-2.1.5.jar
 file:/D:/maven-local-repo/com/thoughtworks/xstream/xstream/1.4.2/xstream-1.4.2.jar
 file:/D:/maven-local-repo/xmlpull/xmlpull/1.1.3.1/xmlpull-1.1.3.1.jar
 file:/D:/maven-local-repo/xpp3/xpp3_min/1.1.4c/xpp3_min-1.1.4c.jar
 file:/D:/maven-local-repo/org/springframework/cloud/spring-cloud-starter-feign/1.1.0.BUILD-SNAPSHOT/spring-cloud-starter-feign-1.1.0.BUILD-20160506.201306-377.jar
 file:/D:/maven-local-repo/org/springframework/spring-web/4.2.6.RELEASE/spring-web-4.2.6.RELEASE.jar
 file:/D:/maven-local-repo/com/netflix/feign/feign-core/8.16.2/feign-core-8.16.2.jar
 file:/D:/maven-local-repo/org/jvnet/animal-sniffer-annotation/1.0/animal-sniffer-annotation-1.0.jar
 file:/D:/maven-local-repo/com/netflix/feign/feign-slf4j/8.16.2/feign-slf4j-8.16.2.jar
 file:/D:/maven-local-repo/com/netflix/feign/feign-hystrix/8.16.2/feign-hystrix-8.16.2.jar
 file:/D:/maven-local-repo/com/netflix/hystrix/hystrix-core/1.5.2/hystrix-core-1.5.2.jar
 file:/D:/maven-local-repo/org/hdrhistogram/HdrHistogram/2.1.7/HdrHistogram-2.1.7.jar
 file:/D:/maven-local-repo/sgcib/ctt/cascade/onyx-util/16.5.4/onyx-util-16.5.4.jar
 file:/D:/maven-local-repo/com/fasterxml/jackson/dataformat/jackson-dataformat-xml/2.6.6/jackson-dataformat-xml-2.6.6.jar
 file:/D:/maven-local-repo/com/fasterxml/jackson/core/jackson-core/2.6.6/jackson-core-2.6.6.jar
 file:/D:/maven-local-repo/com/fasterxml/jackson/core/jackson-annotations/2.6.6/jackson-annotations-2.6.6.jar
 file:/D:/maven-local-repo/com/fasterxml/jackson/module/jackson-module-jaxb-annotations/2.6.6/jackson-module-jaxb-annotations-2.6.6.jar
 file:/D:/maven-local-repo/org/codehaus/woodstox/stax2-api/3.1.4/stax2-api-3.1.4.jar
 file:/D:/maven-local-repo/com/mangofactory/swagger-springmvc/1.0.1/swagger-springmvc-1.0.1.jar
 file:/D:/maven-local-repo/com/wordnik/swagger-annotations/1.3.11/swagger-annotations-1.3.11.jar
 file:/D:/maven-local-repo/com/google/guava/guava/18.0/guava-18.0.jar
 file:/D:/maven-local-repo/com/fasterxml/classmate/1.1.0/classmate-1.1.0.jar
 file:/D:/maven-local-repo/joda-time/joda-time/2.8.2/joda-time-2.8.2.jar
 file:/D:/maven-local-repo/org/springframework/spring-webmvc/4.2.6.RELEASE/spring-webmvc-4.2.6.RELEASE.jar
 file:/D:/maven-local-repo/com/mangofactory/swagger-models/1.0.1/swagger-models-1.0.1.jar
 file:/D:/maven-local-repo/de/codecentric/spring-boot-admin-starter-client/1.3.2/spring-boot-admin-starter-client-1.3.2.jar
 file:/D:/maven-local-repo/org/jolokia/jolokia-core/1.3.3/jolokia-core-1.3.3.jar
 file:/D:/maven-local-repo/com/googlecode/json-simple/json-simple/1.1.1/json-simple-1.1.1.jar
 file:/D:/maven-local-repo/net/logstash/logback/logstash-logback-encoder/4.5.1/logstash-logback-encoder-4.5.1.jar
 file:/D:/maven-local-repo/ch/qos/logback/logback-core/1.1.7/logback-core-1.1.7.jar
 file:/D:/maven-local-repo/org/hibernate/hibernate-validator/5.2.4.Final/hibernate-validator-5.2.4.Final.jar
 file:/D:/maven-local-repo/org/jboss/logging/jboss-logging/3.3.0.Final/jboss-logging-3.3.0.Final.jar
 file:/D:/maven-local-repo/org/springframework/spring-jms/4.2.6.RELEASE/spring-jms-4.2.6.RELEASE.jar
 file:/D:/maven-local-repo/org/springframework/spring-messaging/4.2.6.RELEASE/spring-messaging-4.2.6.RELEASE.jar
 file:/D:/maven-local-repo/org/springframework/spring-tx/4.2.6.RELEASE/spring-tx-4.2.6.RELEASE.jar
 file:/D:/maven-local-repo/org/springframework/boot/spring-boot-starter-actuator/1.3.4.RELEASE/spring-boot-starter-actuator-1.3.4.RELEASE.jar
 file:/D:/maven-local-repo/org/springframework/boot/spring-boot-actuator/1.3.4.RELEASE/spring-boot-actuator-1.3.4.RELEASE.jar
 file:/D:/maven-local-repo/org/springframework/boot/spring-boot-starter-logging/1.3.4.RELEASE/spring-boot-starter-logging-1.3.4.RELEASE.jar
 file:/D:/maven-local-repo/ch/qos/logback/logback-classic/1.1.7/logback-classic-1.1.7.jar
 file:/D:/maven-local-repo/org/slf4j/jcl-over-slf4j/1.7.21/jcl-over-slf4j-1.7.21.jar
 file:/D:/maven-local-repo/org/slf4j/jul-to-slf4j/1.7.21/jul-to-slf4j-1.7.21.jar
 file:/D:/maven-local-repo/org/slf4j/log4j-over-slf4j/1.7.21/log4j-over-slf4j-1.7.21.jar
 file:/D:/maven-local-repo/org/springframework/boot/spring-boot-starter-web/1.3.4.RELEASE/spring-boot-starter-web-1.3.4.RELEASE.jar
 file:/D:/maven-local-repo/org/springframework/boot/spring-boot-starter-tomcat/1.3.4.RELEASE/spring-boot-starter-tomcat-1.3.4.RELEASE.jar
 file:/D:/maven-local-repo/org/apache/tomcat/embed/tomcat-embed-core/8.0.33/tomcat-embed-core-8.0.33.jar
 file:/D:/maven-local-repo/org/apache/tomcat/embed/tomcat-embed-el/8.0.33/tomcat-embed-el-8.0.33.jar
 file:/D:/maven-local-repo/org/apache/tomcat/embed/tomcat-embed-logging-juli/8.0.33/tomcat-embed-logging-juli-8.0.33.jar
 file:/D:/maven-local-repo/org/apache/tomcat/embed/tomcat-embed-websocket/8.0.33/tomcat-embed-websocket-8.0.33.jar
 file:/D:/maven-local-repo/org/springframework/boot/spring-boot-starter-validation/1.3.4.RELEASE/spring-boot-starter-validation-1.3.4.RELEASE.jar
 file:/D:/maven-local-repo/javax/inject/javax.inject/1/javax.inject-1.jar
 file:/D:/maven-local-repo/javax/validation/validation-api/1.1.0.Final/validation-api-1.1.0.Final.jar
 file:/E:/opt/IntelliJ%20IDEA%2015.0.3/lib/idea_rt.jar]
```

**Comment by joshiste** [comment] 2016-05-09 15:56
duplicate of #167 .
The current master / snapshot is compatible with the current `Brixton.BUILD-SNAPSHOT` which has compiler-incompatible changes after the `RC2`

**Closed by joshiste** 2016-05-09 15:56 UTC

**Comment by joshiste** [comment] 2016-05-09 19:38
P.S. an earlier release is not possible. The dependency on spring-cloud-netflix is not optional because zuul is used internally.

**Comment by joshiste** [comment] 2016-05-09 19:39
P.P.S. that's one of the reasons why I repeatedly advise people not to include the admin server into their apps.

**Comment by ouaibsky** [comment] 2016-05-10 10:59
Fair enough
Thx for the answer
