### ISSUE TITLE
set context-path=/admin, turbine is not working

### ISSUE THREAD

**Issue by Consider007** [codecentric/spring-boot-admin#370] opened 2016-12-27 12:47 UTC
1. With spring-boot-admin-server-ui-turbine
2. Config: spring.boot.admin.context-path = /admin
3. Visit page http://localhost:8080/admin/#/turbine
   Error info: Unable to connect to Command Metric Stream 'api/turbine/stream?cluster=default'
   Because UI js invoker api "http://localhost:8080/admin/api/turbine/stream?cluster=default" cannot find!
4. View TurbineAutoConfiguration code, new StaticRouteLocator do not use AdminServerProperties.contextPath, but use ServerProperties.servletPath, 
   Because ServerProperties.servletPath is "", route url is: http://localhost:8080/api/turbine/stream

**Comment by joshiste** [comment] 2016-12-27 13:03
duplicate of #341

**Closed by joshiste** 2016-12-27 13:03 UTC
