### ISSUE TITLE
No way to leverage Spring boot admin UI components when adding custom pages

### ISSUE THREAD

**Issue by Kieun** [codecentric/spring-boot-admin#2582] opened 2023-06-28 08:10 UTC
While upgrading the Spring boot admin 3+ from 2.7x with custom UI, I found that there are some of UI components in the SBA UI and I try to use it, but there seems to be no way to access the components.

It would good to have a way to access the components and leverages them in the custom UI or pages.

**Comment by erikpetzold** [comment] 2023-06-28 08:53
Seems this is a duplicate of #1877

**Comment by iuliiasobolevska** [comment] 2023-07-05 05:58
+100 to the request, if that helps here is a list of components we would greatly benefit from:
`sba-alert`, `sba-filter`, `sba-button`, `sba-icon-button`, `sba-instance-section`, ``sba-panel`

**Comment by SteKoe** [comment] 2023-07-07 06:48
Hi all,

it is possible to use the components already, as they are registered as global components (c.f. https://vuejs.org/guide/components/registration.html#global-registration). 

I have created a Gist that shows a working Vue-View [here](https://gist.github.com/SteKoe/b464f281daea5c7cd1e5bf349e146158).

The result looks like following picture:
![sba-components-usage](https://github.com/codecentric/spring-boot-admin/assets/1809221/acaf533d-0885-4134-9f46-1a763f21668d)

Please check if this is working for you. 

Regards
Stephan

**Closed** 2023-07-28 06:14 UTC
Labels: enhancement
