### ISSUE TITLE
[SBA3 UI] Sidebar gets closed on click on a custom view

### ISSUE THREAD

**Issue by iuliiasobolevska** [codecentric/spring-boot-admin#2593] opened 2023-07-05 06:06 UTC
## Spring Boot Admin Server information

- **Version**:
`3.0.4`

- **Spring Boot version**:
`3.0.6`

## Description
Sidebar gets closed on click on a custom view.

### What happens:

During SBA views initialization, views are first created, then registered in the router using the same proxied view in both.

During custom views initialization, a view is first cloned from the view template (in `viewRegistry.addView()`) with a new view object never being returned, then the original view template is used to register the view in the router (in `viewRegistry.router.addRoute()`).

As a result, when the sidebar is checking if the current group is active it fails to match the view template stored in the router to the view stored in the view registry. The following code always returns `false` for custom views:
```
    isActiveGroup(group) {
      return group.views.includes(this.$route.meta.view);
    },
```

**Comment by erikpetzold** [comment] 2023-07-07 08:44
Hi @iuliiasobolevska 

we were not able to reproduce this issue.

The sidebar is shown only for views referring to instances (`parent: "instances"`).
Custom views in the top navigation bar are not expected to have the sidebar.

However we discovered another bug, multiple custom views in a custom group did not expand. This was fixed with 8a5266cb8c29226b9021c8b32b2cfaaa90436814 and touched the same source snippets you mentioned, so maybe your issue is also fixed?

**Closed** 2023-07-28 06:15 UTC
Labels: bug
