### ISSUE TITLE
Failing request on metrics redirect to login page 

### ISSUE THREAD

**Issue by feliixx** [codecentric/spring-boot-admin#1640] opened 2021-02-21 22:46 UTC
Hi, first of all thanks for this software, it's amanzing !

We've noticed something weird after upgrading our spring-boot-admin instance from **2.3.1** to **2.4.0**: when browsing instance details, after a random delay ( 5 - 30s )  users are automatically redirected to the login page

console log: 

![console](https://user-images.githubusercontent.com/10615565/108641063-637cdd80-74f1-11eb-8c88-294b2f5dbd78.png)

The metrics causing the errors are not always the same: 

- http://spring-boot-admin/instances/f4933231d1f3/actuator/metrics/jvm.memory.max?tag=area:heap
- http://spring-boot-admin/instances/f4933231d1f3/actuator/metrics/jvm.memory.used?tag=area:nonheap,id:Metaspace
- http://spring-boot-admin/instances/f4933231d1f3/actuator/metrics/jvm.threads.daemon

Instance details: 

- spring-boot-admin-server 2.4.0
- spring-boot 2.4.3
- java 11
- auth mod: LDAP

**Server configuration**: 

```
spring.boot.admin.monitor.status-interval = 30000
spring.boot.admin.monitor.status-lifetime = 30000
spring.boot.admin.monitor.default-timeout = 30000
spring.boot.admin.monitor.default-retries = 1
```

**Client configuration**: 

```
spring.boot.admin.client.url     = http://spring-boot-admin/
spring.boot.admin.client.enabled = true
spring.boot.admin.client.instance.metadata.tags.environment = production

management.info.git.mode                  = full
management.health.mail.enabled            = false
management.health.ldap.enabled            = false

management.endpoints.web.exposure.include = *
management.endpoint.health.show-details   = always
management.endpoint.liquibase.enabled     = false
management.endpoint.beans.enabled         = false
management.endpoint.caches.enabled        = false
management.endpoint.threaddump.enabled    = false
management.endpoint.shutdown.enabled      = false
management.endpoint.heapdump.enabled      = false
management.endpoint.conditions.enabled    = false
management.endpoint.jolokia.enabled       = false


spring.security.user.name         = springbootadmin-user
spring.security.user.password     = xxxxxxx
spring.boot.admin.client.username = ${spring.security.user.name}
spring.boot.admin.client.password = ${spring.security.user.password}
spring.boot.admin.client.instance.metadata.user.name        = ${spring.security.user.name}
spring.boot.admin.client.instance.metadata.user.password    = ${spring.security.user.password}
```

**Comment by robtha** [comment] 2021-02-22 06:35
I had the same problem after upgrading. In my case the problem occured on insight details if the client
has disabled system metrics.
browser console shows a javascript errors after an HTTP 404 error when it tries to access disabled metrics. then it redirects to the login page.

**Comment by mikhalchenko-alexander** [comment] 2021-02-23 12:56
Same here. It seems that authorization is broken. When I set up security like this
```
http
  .authorizeRequests()
  .antMatchers(adminServer.contextPath + "/assets/**").permitAll()
  .antMatchers(adminServer.contextPath + "/login").permitAll()
  .anyRequest().authenticated()
```
I get 401 error for
```
http://127.0.0.1:8888/instances/82dc18825541/actuator/env/PID
http://127.0.0.1:8888/instances/82dc18825541/actuator/metrics/process.uptime
http://127.0.0.1:8888/instances/82dc18825541/actuator/metrics/system.cpu.count
```
And then I redirected to login. But with this configuration 
```
http
  .authorizeRequests()
  .antMatchers("/**").permitAll()
```
everything works.

I have this behavior after upgrading to 2.4.0. In 2.3.1 both configuration are working.

**Comment by mikhalchenko-alexander** [comment] 2021-02-23 15:02
I've turned on 'Remember me' feature as described in [this example](https://github.com/codecentric/spring-boot-admin/blob/master/spring-boot-admin-samples/spring-boot-admin-sample-servlet/src/main/java/de/codecentric/boot/admin/SecuritySecureConfig.java) and it works normally if I check 'Remember me' box when logging in to admin UI. If I don't check the checkbox I get 401 and then I redirected to login page.

**Comment by joshiste** [comment] 2021-02-26 07:25
The UI redirecting on a 401 for a metrics request looks like a bug to me. 

The config https://github.com/codecentric/spring-boot-admin/blob/6e12776b9d3e80b00c443d3688f3703354b4bfe2/spring-boot-admin-server-ui/src/main/frontend/services/instance.js#L42 in should excempt the actuator endpoints from a redirect.

But the 401 for the metrics itself is up to your spring security config

**Comment by uklance** [comment] 2021-03-01 10:42
I hit this issue when trying to add security to SBA following the steps at https://www.baeldung.com/spring-boot-admin. I was able to get it working by downgrading to `spring-boot-admin-starter-server` version `2.3.1` 

To diagnose the issues I switched on debugging in logback.xml
```xml
<logger name="org.springframework.security" level="DEBUG" />
```

And I saw these entries in the logs
```
2021-03-01 08:43:45.571 DEBUG 16620 --- [nio-8084-exec-5] o.s.s.w.a.i.FilterSecurityInterceptor    : Failed to authorize filter invocation [GET /instances/a973ff14be49/actuator/metrics/process.uptime] with attributes [authenticated]
2021-03-01 08:43:45.571 DEBUG 16620 --- [nio-8084-exec-4] o.s.s.w.a.i.FilterSecurityInterceptor    : Failed to authorize filter invocation [GET /instances/a973ff14be49/actuator/env/PID] with attributes [authenticated]
2021-03-01 08:43:45.586 DEBUG 16620 --- [nio-8084-exec-6] o.s.s.w.a.i.FilterSecurityInterceptor    : Failed to authorize filter invocation [GET /instances/a973ff14be49/actuator/metrics/system.cpu.count] with attributes [authenticated]
2021-03-01 08:43:45.586 DEBUG 16620 --- [nio-8084-exec-6] o.s.s.w.a.i.FilterSecurityInterceptor    : Failed to authorize filter invocation [GET /instances/a973ff14be49/actuator/metrics/process.cpu.usage] with attributes [authenticated]
2021-03-01 08:43:45.586 DEBUG 16620 --- [nio-8084-exec-8] o.s.s.w.a.i.FilterSecurityInterceptor    : Failed to authorize filter invocation [GET /instances/a973ff14be49/actuator/metrics/system.cpu.usage] with attributes [authenticated]
2021-03-01 08:43:45.586 DEBUG 16620 --- [nio-8084-exec-9] o.s.s.w.a.i.FilterSecurityInterceptor    : Failed to authorize filter invocation [GET /instances/a973ff14be49/actuator/metrics/jvm.threads.live] with attributes [authenticated]
2021-03-01 08:43:45.602 DEBUG 16620 --- [io-8084-exec-10] o.s.s.w.a.i.FilterSecurityInterceptor    : Failed to authorize filter invocation [GET /instances/a973ff14be49/actuator/metrics/jvm.threads.peak] with attributes [authenticated]
2021-03-01 08:43:45.602 DEBUG 16620 --- [nio-8084-exec-3] o.s.s.w.a.i.FilterSecurityInterceptor    : Failed to authorize filter invocation [GET /instances/a973ff14be49/actuator/metrics/jvm.threads.daemon] with attributes [authenticated]
2021-03-01 08:43:45.602 DEBUG 16620 --- [nio-8084-exec-1] o.s.s.w.a.i.FilterSecurityInterceptor    : Failed to authorize filter invocation [GET /instances/a973ff14be49/actuator/metrics/jvm.memory.max?tag=area:heap] with attributes [authenticated]
2021-03-01 08:43:45.602 DEBUG 16620 --- [nio-8084-exec-4] o.s.s.w.a.i.FilterSecurityInterceptor    : Failed to authorize filter invocation [GET /instances/a973ff14be49/actuator/metrics/jvm.memory.max?tag=area:nonheap] with attributes [authenticated]
2021-03-01 08:43:45.602 DEBUG 16620 --- [nio-8084-exec-4] o.s.s.w.a.i.FilterSecurityInterceptor    : Failed to authorize filter invocation [GET /instances/a973ff14be49/actuator/metrics/jvm.memory.used?tag=area:nonheap] with attributes [authenticated]
2021-03-01 08:43:45.602 DEBUG 16620 --- [nio-8084-exec-2] o.s.s.w.a.i.FilterSecurityInterceptor    : Failed to authorize filter invocation [GET /instances/a973ff14be49/actuator/metrics/jvm.memory.used?tag=area:heap] with attributes [authenticated]
```

**Comment by zhangran2616** [comment] 2021-04-12 03:47
Is the problem solved？

**Comment by mikhalchenko-alexander** [comment] 2021-04-19 10:55
Just tested the fix. It does not redirect to login anymore. But all endpoints now return 401 and I cannot get any info from client instances unless I tick 'Remember me' checkbox on login page. So without 'Remember me' the admin UI becomes useless.

**Comment by gbtec-ext-fernandoquiroga** [comment] 2021-05-04 07:15
Why is this issue closed? The 401 is still happening in version 2.4.1, the UI solution only prevents by getting redirected to the login page but the 401 errors are still happening.

**Comment by albrechtm85** [comment] 2021-07-05 10:20
Upgraded to 2.4.2, still getting a 401 on metrics calls...

**Comment by albrechtm85** [comment] 2021-07-07 14:58
> Upgraded to 2.4.2, still getting a 401 on metrics calls...

ah upgrading to 2.4.3 fixes the problem for me

**Comment by kaplan441** [comment] 2021-07-08 10:26
I use 2.4.3 and this security config [https://github.com/codecentric/spring-boot-admin/blob/master/spring-boot-admin-samples/spring-boot-admin-sample-servlet/src/main/java/de/codecentric/boot/admin/SecuritySecureConfig.java](url). But still without remember me, it redirect to login and in metric details screen has 401.

How can i fix it?

**Comment by vikinghawk** [comment] 2022-01-25 22:24
I'm seeing this as well on 2.6.x.

Open dev tools on the application instance details page and about 5-10% of requests for jvm metric GETs are responding with 302 redirects to the /login endpoint.

**Comment by fuerstjh** [comment] 2022-04-28 14:30
I'm also seeing this on 2.6.X. I just moved back to 2.3.1 and the issue was resolved. 

I can't help but feel this is related to how SBA is tracking the sessions? If I visit pages within the UI that have only a few ajax calls ( such as Loggers ) it all works fine. The moment I hit the Insights->Details page ( which has lots of metric calls via ajax ) 302s start blowing up the Ajax calls. Once that process starts happening, navigating back to the Loggers page now fails to pull information ( 302 redirect ). 

Sadly I can't share my code, but I've spun this up locally and disabled all security on the sba-client services and still see the same issue.

**Comment by erikpetzold** [comment] 2022-04-29 09:08
Hi @vikinghawk and @fuerstjh 

if you think there is still a problem, please reopen the issue. Comments on closed issues may get overseen.

@fuerstjh if you can reproduce it locally, maybe you can copy the app, remove all private stuff and then provide an demo app for us?

**Comment by fuerstjh** [comment] 2022-05-03 17:28
I've created a repo here: https://github.com/fuerstjh/spring-boot-admin-issue which seems to be displaying the same issue I am seeing internally. It doesn't fully manifest in the same way, but I'll explain further. 

If you pull down that repo and run (details in readme) hopefully you will see random 401's crop up in the dev tools network view ( chrome ). This honestly doesn't seem to cause a visible issue within the SBA UI. Internally we are authenticating with an external provider. I *THINK* what is happening is randomly one of these 401's occur which causes SBA to throw away the cached token ( invalidating the session/cookie ). This means all further ajax requests will get 302's back to auth again ( which then get blocked due to CORS ). 

My gut tells me solving the random 401's. will fix my issue internally, but I can't be 100% sure.

@erikpetzold  Would you like me to create a new issue? Not an avid  OS contributor and I don't seem to have the ability to "re-open" this one. :-)

**Comment by SteKoe** [comment] 2022-07-08 08:57
Hi,
thank you very much for providing the demo repository! Using the given implementation we could reproduce the issue and compared two requests, one failing, and one working with the following results:

## Output of failing request
```
2022-07-08 10:48:49.656 DEBUG 41197 --- [io-8080-exec-11] o.s.security.web.FilterChainProxy        : Securing GET /assets/js/chunk-vendors.1da91485.js.map
2022-07-08 10:48:49.656 TRACE 41197 --- [io-8080-exec-11] w.c.HttpSessionSecurityContextRepository : Did not find SecurityContext in HttpSession 0950CC70AE13951E12F7C68571170F0E using the SPRING_SECURITY_CONTEXT session attribute
2022-07-08 10:48:49.656 TRACE 41197 --- [io-8080-exec-11] w.c.HttpSessionSecurityContextRepository : Created SecurityContextImpl [Null authentication]
2022-07-08 10:48:49.656 DEBUG 41197 --- [io-8080-exec-11] s.s.w.c.SecurityContextPersistenceFilter : Set SecurityContextHolder to empty SecurityContext
2022-07-08 10:48:49.657 DEBUG 41197 --- [io-8080-exec-11] o.s.s.w.a.AnonymousAuthenticationFilter  : Set SecurityContextHolder to anonymous SecurityContext
2022-07-08 10:48:49.657 DEBUG 41197 --- [io-8080-exec-11] o.s.s.w.a.i.FilterSecurityInterceptor    : Authorized filter invocation [GET /assets/js/chunk-vendors.1da91485.js.map] with attributes [permitAll]
2022-07-08 10:48:49.657 DEBUG 41197 --- [io-8080-exec-11] o.s.security.web.FilterChainProxy        : Secured GET /assets/js/chunk-vendors.1da91485.js.map
2022-07-08 10:48:49.661 DEBUG 41197 --- [io-8080-exec-11] w.c.HttpSessionSecurityContextRepository : Did not store anonymous SecurityContext
```

## Output of working request
```
2022-07-08 10:48:52.116 DEBUG 41197 --- [nio-8080-exec-6] o.s.security.web.FilterChainProxy        : Securing GET /instances/1b65fbb13f43/actuator/metrics/jvm.threads.live
2022-07-08 10:48:52.117 TRACE 41197 --- [nio-8080-exec-6] w.c.HttpSessionSecurityContextRepository : Retrieved SecurityContextImpl [Authentication=UsernamePasswordAuthenticationToken [Principal=org.springframework.security.core.userdetails.User [Username=admin, Password=[PROTECTED], Enabled=true, AccountNonExpired=true, credentialsNonExpired=true, AccountNonLocked=true, Granted Authorities=[]], Credentials=[PROTECTED], Authenticated=true, Details=WebAuthenticationDetails [RemoteIpAddress=0:0:0:0:0:0:0:1, SessionId=null], Granted Authorities=[]]] from SPRING_SECURITY_CONTEXT
2022-07-08 10:48:52.118 DEBUG 41197 --- [nio-8080-exec-6] s.s.w.c.SecurityContextPersistenceFilter : Set SecurityContextHolder to SecurityContextImpl [Authentication=UsernamePasswordAuthenticationToken [Principal=org.springframework.security.core.userdetails.User [Username=admin, Password=[PROTECTED], Enabled=true, AccountNonExpired=true, credentialsNonExpired=true, AccountNonLocked=true, Granted Authorities=[]], Credentials=[PROTECTED], Authenticated=true, Details=WebAuthenticationDetails [RemoteIpAddress=0:0:0:0:0:0:0:1, SessionId=null], Granted Authorities=[]]]
2022-07-08 10:48:52.118 DEBUG 41197 --- [nio-8080-exec-6] s.s.w.a.r.RememberMeAuthenticationFilter : SecurityContextHolder not populated with remember-me token, as it already contained: 'UsernamePasswordAuthenticationToken [Principal=org.springframework.security.core.userdetails.User [Username=admin, Password=[PROTECTED], Enabled=true, AccountNonExpired=true, credentialsNonExpired=true, AccountNonLocked=true, Granted Authorities=[]], Credentials=[PROTECTED], Authenticated=true, Details=WebAuthenticationDetails [RemoteIpAddress=0:0:0:0:0:0:0:1, SessionId=null], Granted Authorities=[]]'
2022-07-08 10:48:52.118 DEBUG 41197 --- [nio-8080-exec-6] o.s.s.w.a.i.FilterSecurityInterceptor    : Authorized filter invocation [GET /instances/1b65fbb13f43/actuator/metrics/jvm.threads.live] with attributes [authenticated]
2022-07-08 10:48:52.118 DEBUG 41197 --- [nio-8080-exec-6] o.s.security.web.FilterChainProxy        : Secured GET /instances/1b65fbb13f43/actuator/metrics/jvm.threads.live
```

As you can see, in the failing case the SecurityContext was not retrieved from the HttpSession even though the session id has not changed. We assume that this is related to this open bug in Spring Security and hence not related to SBA: https://github.com/spring-projects/spring-security/issues/2968

We will keep an eye on the issue mentioned above but close this one.

**Closed by SteKoe** 2022-07-08 08:57 UTC
Labels: bug, server-ui
