### ISSUE TITLE
Pls handle -> BeanCreationNotAllowedException #833

### ISSUE THREAD

**Issue by luodongseu** [codecentric/spring-boot-admin#1258] opened 2019-09-12 13:39 UTC
I have the same error when shutdown spring cloud project with feign clients;

pls solve  it!

Demo is here: BeanCreationNotAllowedException #833

**Comment by joshiste** [comment] 2019-09-13 21:23
@luodongseu I don't know. I haven't looked at the sample project, as it is pretty outdated. And I'm lacking the time to reproduce the error from scratch. So If you want me to have a look at it please provide an up-to-date sample to reproduce the error.

**Comment by joshiste** [comment] 2019-09-13 21:28
> Is that we need implements BeanFactoryPostProcessor to set feignContext bean depends on registrainListener?

just give it a try.

**Comment by joshiste** [comment] 2019-09-18 19:37
closing due to missing feedback

**Closed by joshiste** 2019-09-18 19:37 UTC
Labels: waiting-for-feedback

**Comment by luodongseu** [comment] 2019-09-25 08:38
Finally, i set bean dependencies in custom BeanFactoryPostProcessor, which like this:
`
BeanDefinition bd1 = beanFactory.getBeanDefinition("feignContext");
bd1.setDependsOn("registrationListener");

BeanDefinition bd2 = beanFactory.getBeanDefinition("springClientFactory");
bd2.setDependsOn("registrationListener");
`
