### ISSUE TITLE
Event 0 must be greater or equal to 1

### ISSUE THREAD

**Issue by zhanglei-1987** [codecentric/spring-boot-admin#1240] opened 2019-08-14 13:12 UTC
2019-08-14 21:08:57.660  WARN 6588 --- [monitor.event-2] b.a.s.d.e.SnapshottingInstanceRepository : Error while updating the snapshot with event InstanceRegisteredEvent(super=InstanceEvent(instance=e0c093fdf80c, version=0, timestamp=2019-08-14T13:08:56.658Z, type=REGISTERED), registration=Registration(name=PGW-UNIONPAY-LEGACY, managementUrl=http://192.168.89.41:8500/pgw-unionpay-legacy/actuator, healthUrl=http://192.168.89.41:8500/pgw-unionpay-legacy/actuator/health, serviceUrl=http://192.168.89.41:8500/pgw-unionpay-legacy, source=discovery))

java.lang.IllegalArgumentException: Event 0 must be greater or equal to 1
	at org.springframework.util.Assert.isTrue(Assert.java:136)
	at de.codecentric.boot.admin.server.domain.entities.Instance.apply(Instance.java:215)
	at de.codecentric.boot.admin.server.domain.entities.Instance.apply(Instance.java:209)
	at de.codecentric.boot.admin.server.domain.entities.SnapshottingInstanceRepository.lambda$updateSnapshot$5(SnapshottingInstanceRepository.java:100)
	at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1877)
	at de.codecentric.boot.admin.server.domain.entities.SnapshottingInstanceRepository.updateSnapshot(SnapshottingInstanceRepository.java:98)
	at reactor.core.publisher.LambdaSubscriber.onNext(LambdaSubscriber.java:130)
	at reactor.core.publisher.FluxConcatArray$ConcatArraySubscriber.onNext(FluxConcatArray.java:176)
	at reactor.core.publisher.FluxPublish$PublishSubscriber.drain(FluxPublish.java:474)
	at reactor.core.publisher.FluxPublish$PublishSubscriber.onNext(FluxPublish.java:253)
	at reactor.core.publisher.UnicastProcessor.drainFused(UnicastProcessor.java:277)
	at reactor.core.publisher.UnicastProcessor.drain(UnicastProcessor.java:310)
	at reactor.core.publisher.UnicastProcessor.onNext(UnicastProcessor.java:386)
	at reactor.core.publisher.FluxCreate$IgnoreSink.next(FluxCreate.java:618)
	at reactor.core.publisher.FluxCreate$SerializedSink.drainLoop(FluxCreate.java:248)
	at reactor.core.publisher.FluxCreate$SerializedSink.next(FluxCreate.java:168)
	at de.codecentric.boot.admin.server.eventstore.InstanceEventPublisher.lambda$publish$0(InstanceEventPublisher.java:44)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at de.codecentric.boot.admin.server.eventstore.InstanceEventPublisher.publish(InstanceEventPublisher.java:42)
	at de.codecentric.boot.admin.server.eventstore.HazelcastEventStore$1.entryUpdated(HazelcastEventStore.java:56)
	at com.hazelcast.map.impl.MapListenerAdaptors$4$1.onEvent(MapListenerAdaptors.java:129)
	at com.hazelcast.map.impl.MapListenerAdaptors$4$1.onEvent(MapListenerAdaptors.java:126)

**Comment by joshiste** [comment] 2019-08-14 16:11
looks like a duplicate of #1231 to me.

**Closed by joshiste** 2019-08-14 16:11 UTC
Labels: duplicate
