### ISSUE TITLE
admin 和 eureka   Asynchrony

### ISSUE THREAD

**Issue by ChenZheOnePiece** [codecentric/spring-boot-admin#1335] opened 2019-12-24 09:38 UTC
this is admin
![1577179852(1)](https://user-images.githubusercontent.com/25056180/71406462-42152d00-2673-11ea-929c-ee1191c4ed85.jpg)
this is eureka 
![1577179877(1)](https://user-images.githubusercontent.com/25056180/71406494-56592a00-2673-11ea-8990-3bab28f78b59.jpg)
when Project just started is  Asynchrony   but when i  restart admin 
![1577180063(1)](https://user-images.githubusercontent.com/25056180/71406599-a9cb7800-2673-11ea-84cb-a67c9d4bb4b4.jpg)
I see can retry Already pulled Monitoring,but can,t Monitoring  not Register eureka , Even if later registered to eureka , Unless restart admin

**Comment by joshiste** [comment] 2019-12-24 10:29
duplicate of #1327

**Closed by joshiste** 2019-12-24 10:29 UTC
Labels: bug, waiting-for-triage
