### ISSUE TITLE
org.springframework.web.util.NestedServletException:Request processing failed; nested exception is java.lang.IllegalStateException: Can't set AsyncWebRequest with concurrent handling in progress

### ISSUE THREAD

**Issue by coder-han** [codecentric/spring-boot-admin#421] opened 2017-03-07 08:54 UTC
### Error
```
org.springframework.web.util.NestedServletException:Request processing failed; nested exception is java.lang.IllegalStateException: Can't set AsyncWebRequest with concurrent handling in progress
```
### application.yml

```
spring:
  application:
    name: benyue-monitor
  cloud:
    config:
      enabled: false
server:
  port: 18001


eureka:
  client:
    service-url:
      defaultZone: http://eureka1:11001/eureka/
    registryFetchIntervalSeconds: 5
  instance:
    ip-address: ${service_ip:127.0.0.1}
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 10

```

This error has been

**Comment by joshiste** [comment] 2017-03-07 10:58
Your description seems incomplete, as the last sentence is incomplete.

**Comment by joshiste** [comment] 2017-03-07 12:40
duplicate of #238

**Closed by joshiste** 2017-03-07 12:40 UTC
Labels: duplicate
