### ISSUE TITLE
Out of Service status looks bad

### ISSUE THREAD

**Issue by beanball** [codecentric/spring-boot-admin#401] opened 2017-02-06 20:12 UTC
I created a custom health indicator which uses the built in status, Out of Service. It looks pretty terrible in the dashboard.

![image](https://cloud.githubusercontent.com/assets/505102/22664408/31b556b8-ec76-11e6-8ce6-b83386b0e631.png)

**Comment by joshiste** [comment] 2017-02-06 20:17
duplicate of #394

**Closed by joshiste** 2017-02-06 20:17 UTC
