### ISSUE TITLE
Spring admin server won't boot up with version 1.4.2

### ISSUE THREAD

**Issue by berinle** [codecentric/spring-boot-admin#287] opened 2016-09-30 10:34 UTC
When attempting to upgrade admin server from 1.3.4 to 1.4.2, I keep getting a classnotfound exception.

    2016-09-30 06:09:38.129  INFO 91676 --- [           main] com.example.DemoApplication              : Starting     DemoApplication on Bayos-MacBook-Pro.local with PID 91676 (/private/tmp/hello_me/build/classes/main started by berinle     in /private/tmp/hello_me)
    2016-09-30 06:09:38.132  INFO 91676 --- [           main] com.example.DemoApplication              : No active profile     set, falling back to default profiles: default
    2016-09-30 06:09:38.190  INFO 91676 --- [           main] ationConfigEmbeddedWebApplicationContext : Refreshing     org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@3a93b025: startup date [Fri Sep     30 06:09:38 EDT 2016]; root of context hierarchy
    2016-09-30 06:09:38.984 ERROR 91676 --- [           main] o.s.boot.SpringApplication               : Application     startup failed
    
    java.lang.IllegalStateException: Could not evaluate condition on org.springframework.cloud.netflix.zuul.ZuulConfiguration#routeLocator due to org/springframework/cloud/netflix/zuul/filters/TraceProxyRequestHelper not found. Make sure your own configuration does not rely on that class. This can also happen if you are @ComponentScanning a springframework package (e.g. if you put a @ComponentScan in the default package by mistake)
        at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:55) ~[spring-boot-autoconfigure-1.4.1.RELEASE.jar:1.4.1.RELEASE]
        at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:102) ~[spring-context-4.3.3.RELEASE.jar:4.3.3.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForBeanMethod(ConfigurationClassBeanDefinitionReader.java:178) ~[spring-context-4.3.3.RELEASE.jar:4.3.3.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:140) ~[spring-context-4.3.3.RELEASE.jar:4.3.3.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:116) ~[spring-context-4.3.3.RELEASE.jar:4.3.3.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:336) ~[spring-context-4.3.3.RELEASE.jar:4.3.3.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:246) ~[spring-context-4.3.3.RELEASE.jar:4.3.3.RELEASE]
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:273) ~[spring-context-4.3.3.RELEASE.jar:4.3.3.RELEASE]
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:98) ~[spring-context-4.3.3.RELEASE.jar:4.3.3.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:681) ~[spring-context-4.3.3.RELEASE.jar:4.3.3.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:523) ~[spring-context-4.3.3.RELEASE.jar:4.3.3.RELEASE]
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.4.1.RELEASE.jar:1.4.1.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:761) [spring-boot-1.4.1.RELEASE.jar:1.4.1.RELEASE]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:371) [spring-boot-1.4.1.RELEASE.jar:1.4.1.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-1.4.1.RELEASE.jar:1.4.1.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1186) [spring-boot-1.4.1.RELEASE.jar:1.4.1.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1175) [spring-boot-1.4.1.RELEASE.jar:1.4.1.RELEASE]
        at com.example.DemoApplication.main(DemoApplication.java:13) [main/:na]
    Caused by: java.lang.NoClassDefFoundError: org/springframework/cloud/netflix/zuul/filters/TraceProxyRequestHelper
        at java.lang.Class.getDeclaredMethods0(Native Method) ~[na:1.8.0_40]
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[na:1.8.0_40]
        at java.lang.Class.getDeclaredMethods(Class.java:1975) ~[na:1.8.0_40]
        at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:612) ~[spring-core-4.3.3.RELEASE.jar:4.3.3.RELEASE]
        at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:524) ~[spring-core-4.3.3.RELEASE.jar:4.3.3.RELEASE]

I created a brand new application and followed the getting started guide @ http://codecentric.github.io/spring-boot-admin/1.4.2/#getting-started and got the same exact error (above).

The dependency list does have the `spring-cloud-netflix-core` but that version doesn't seem to contain `org/springframework/cloud/netflix/zuul/filters/TraceProxyRequestHelper`

    $ gradle dependencyInsight --dependency netflix
    :dependencyInsight
    com.netflix.archaius:archaius-core:0.6.0
    \--- com.netflix.zuul:zuul-core:1.1.0
         \--- de.codecentric:spring-boot-admin-server:1.4.2
              \--- compile
    
    com.netflix.netflix-commons:netflix-commons-util:0.1.1
    \--- com.netflix.zuul:zuul-core:1.1.0
         \--- de.codecentric:spring-boot-admin-server:1.4.2
              \--- compile
    
    com.netflix.servo:servo-core:0.7.2
    \--- com.netflix.zuul:zuul-core:1.1.0
         \--- de.codecentric:spring-boot-admin-server:1.4.2
              \--- compile
    
    com.netflix.zuul:zuul-core:1.1.0
    \--- de.codecentric:spring-boot-admin-server:1.4.2
         \--- compile
    
    org.springframework.cloud:spring-cloud-netflix-core:1.1.0.RELEASE
    \--- de.codecentric:spring-boot-admin-server:1.4.2
         \--- compile
    
    BUILD SUCCESSFUL
    
    Total time: 4.184 secs

**Comment by joshiste** [comment] 2016-09-30 11:53
duplicate of #259. Please look at the SO post referenced in this issue.

**Closed by joshiste** 2016-09-30 11:53 UTC

**Comment by berinle** [comment] 2016-09-30 12:18
Thanks! Sorry, i missed that
