### ISSUE TITLE
UnknownHostException and Too many open files error

### ISSUE THREAD

**Issue by somera** [codecentric/spring-boot-admin#1486] opened 2020-08-03 23:25 UTC
I added Spring Boot Admin to my local infrastructure.

```
    <properties>
        <spring-boot-admin-server.version>2.2.4</spring-boot-admin-server.version>
        <spring-boot-admin-starter-client.version>2.2.4</spring-boot-admin-starter-client.version>
        <spring-boot-admin-server-ui-login.version>1.5.7</spring-boot-admin-server-ui-login.version>
    </properties>
```
and this

```
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.2.8.RELEASE</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>

    <properties>
        <java.version>11</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <spring-cloud.version>Hoxton.SR5</spring-cloud.version>
    </properties>
```

I took 

`https://github.com/codecentric/spring-boot-admin/tree/master/spring-boot-admin-samples/spring-boot-admin-sample-eureka`

and made only small modifications.

Spring Boot Admin got the informations about the services from Eureka cluster (two eureka instances).

![image](https://user-images.githubusercontent.com/8334250/89236528-20a8f600-d5f1-11ea-9662-da8c7564262b.png)

After ~1-2h I got a lot of errors. Here as screenshot cause copy&paste from ELK Stack.

![image](https://user-images.githubusercontent.com/8334250/89236285-6a451100-d5f0-11ea-9ee3-fb197c226c42.png)

![image](https://user-images.githubusercontent.com/8334250/89236311-792bc380-d5f0-11ea-8a7e-b7e32390fce5.png)

In this time I had no problems in my infrastructure. All the services are working fine.

**Comment by joshiste** [comment] 2020-08-04 09:55
duplicate of #1459

**Closed by joshiste** 2020-08-04 09:55 UTC
Labels: duplicate
