### ISSUE TITLE
Any plan for new coming spring cloud and spring boot

### ISSUE THREAD

**Issue by perdonare** [codecentric/spring-boot-admin#595] opened 2017-11-23 08:25 UTC
Current I Use spring cloud Finchley and spring boot M3 found difficult to Integration
 
as spring showing   Finchley will released at January 15, 2018 
and spring boot 2.0 will released at February 20, 2018

Any plan for update to Finchley?

**Comment by joshiste** [comment] 2017-11-23 21:26
duplicate of #465

**Closed by joshiste** 2017-11-23 21:26 UTC
