### ISSUE TITLE
[feature request] do you consider some management functionality to start/stop/restart/deploy services?

### ISSUE THREAD

**Issue by archenroot** [codecentric/spring-boot-admin#594] opened 2017-11-18 22:35 UTC
Do you consider to integrate such functionality?

Otherwise this application really rocks and I am going to use this on my new project. Extensions for configuration parts and integration with eureka/consul simply rocks.

**Comment by joshiste** [comment] 2017-11-24 05:21
duplicate of #99

**Closed by joshiste** 2017-11-24 05:21 UTC
