### ISSUE TITLE
Description Failed to `exclude /actuator/**` the HTTP trace

### ISSUE THREAD

**Issue by wangpeicong1998** [codecentric/spring-boot-admin#2103] opened 2022-08-01 09:26 UTC
When only management-base-URL is configured, the Springboot-admin tool cannot filter the option of `exclude /actuator/**`,
When prefer-IP and management-base-URL are configured simultaneously, You can use the Exclude function

Use version：
```xml
<groupId>org.mybatis.spring.boot</groupId>
<artifactId>mybatis-spring-boot-starter</artifactId>
<version>2.6.7</version>

<groupId>de.codecentric</groupId>
<artifactId>spring-boot-admin-starter-client</artifactId>
<version>2.5.1</version>
```

**Comment by wangpeicong1998** [comment] 2022-08-03 02:46
@Johannes Edmeier

**Comment by wangpeicong1998** [comment] 2022-08-03 02:47
@joshiste

**Comment by wangpeicong1998** [comment] 2022-08-04 03:06
@erikpetzold

**Comment by ulischulte** [comment] 2022-08-05 07:36
Hi @wangpeicong1998,

A little bit more information is required to check your issue. How are client and server deployed and communicating with each other (war/standalone/servlet/docker etc.)?
Please provide a test case or sample application and/or configuration file if possible.
Ideally, you could provide us with a repository that we can use to reproduce the error.

Regards,
Uli

**Comment by ulischulte** [comment] 2022-08-12 06:17
@wangpeicong1998

**Comment by ulischulte** [comment] 2022-08-19 07:41
Hi @wangpeicong1998,

since we're not receiving any response, we're closing this issue right now. 
Some hints that might solve your problem:
The filter 'actuator/**' is shown if the `managementUrl` includes the registered `serviceUrl`. This means for instance, if you configure separate application and management ports, you won't find this filter (which might be your case). A solution for you might be configuring `spring.boot.admin.client.instance.service-url`.

Regards,
Uli

**Closed by ulischulte** 2022-08-19 07:41 UTC
Labels: bug, waiting-for-feedback
