### ISSUE TITLE
Error in custom view

### ISSUE THREAD

**Issue by wangChengChao** [codecentric/spring-boot-admin#1411] opened 2020-04-30 02:31 UTC
I encountered an error while customizing the view:

applications:1 Refused to apply style from 'http://localhost:8081/custom/css/custom.cfd56467.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
applications:1 Refused to execute script from 'http://localhost:8081/custom/js/custom.566881f4.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

I want to know how to solve？
Thanks！

**Comment by joshiste** [comment] 2020-04-30 06:48
duplicate of #1342

**Closed by joshiste** 2020-04-30 06:48 UTC
Labels: duplicate
