### ISSUE TITLE
Question about Environment function under managementContext

### ISSUE THREAD

**Issue by yazhishu** [codecentric/spring-boot-admin#686] opened 2018-03-28 07:22 UTC
hello everyone,
    When I set management.port and management.context-path in eureka.instance.metadataMap,I found that the editBox under Environment is disappeared,and the refresh http request '/api/applications/xxxxx/refresh' response 500 which should response 405 in normal.
    I read the source code and try to find a solution,and then,I find it will new a DispatcherServlet to handle management request.In this DispatcherServlet,there is only one HandlerExceptionResolver is set.It's CompositeHandlerExceptionResolver which is defined in EndpointWebMvcChildContextConfiguration.The CompositeHandlerExceptionResolver will get a list of ExceptionResolvers but delete itself at last.When there is only one ExceptionResolver,the problem above happened.
    I autowired a DefaultHandlerExceptionResolver in ManagementContext,and it worked.Now I can edit thd Environment properties again.
    I want to know why this happened and if there is any better solution to solve this problem,thanks a lot.

**Comment by joshiste** [comment] 2018-03-28 07:46
resolving the root cause of the 500 should be a better option.

**Closed by joshiste** 2018-03-28 07:46 UTC
