### ISSUE TITLE
Documentation: Customizing the InstanceWebClient

### ISSUE THREAD

**Issue by only1geordie** [codecentric/spring-boot-admin#1094] opened 2019-02-13 21:34 UTC
I have enabled https on deployed services. When spring-admin makes actuator calls. I get authorisation errors. The services have role based authentication against the actuator endpoints. So I want to use a client cert. When I remove the role requirements it all works. I believe the spring-admin server is using the server cert for the sslcontext when making the call. I have recreated the webinstance with a custom web client. But does not seem to be used. The netty sslhandler does not use the client sslcontext. Can anyone advise how to do this.

**Comment by joshiste** [comment] 2019-02-27 09:25
As #1019 is requesting a better solution for customizing the WebClient it should also include a appropriate example. I'm closing this as duplicate of #1019.

**Closed by joshiste** 2019-02-27 09:25 UTC
Labels: documentation
