### ISSUE TITLE
Client unable to register when app depends on netty

### ISSUE THREAD

**Issue by chochos** [codecentric/spring-boot-admin#255] opened 2016-08-25 16:42 UTC
I have a bunch of spring boot apps that are being monitored without any problems, except for one which has problems registering. The only difference between this app and the others is it uses netty. I've tried different versions of 4.0 and even 4.1 and the problem persists.

On the client side (my app) this comes up at startup time:

2016-08-25 11:29:22.455  WARN 62687 --- [pool-1-thread-1] d.c.b.a.services.ApplicationRegistrator  : Failed to register application as Application [id=null, name=tx, managementUrl=http://192.168.1.64:8080, healthUrl=http://192.168.1.64:8080/health, serviceUrl=http://192.168.1.64:8080] at spring-boot-admin ([http://localhost:7015/api/applications]): 400

And this shows up on the server (the spring boot admin):

2016-08-25 11:30:41.777  WARN 62678 --- [nio-7015-exec-5] .w.s.m.s.DefaultHandlerExceptionResolver : Failed to read HTTP message: org.springframework.http.converter.HttpMessageNotReadableException: Required request body is missing: public org.springframework.http.ResponseEntity<de.codecentric.boot.admin.model.Application> de.codecentric.boot.admin.registry.web.RegistryController.register(de.codecentric.boot.admin.model.Application)

You can even test this with a sample spring boot app, just add `io.netty:netty-codec-http:4.0.40.Final` to the dependencies. I'm using Spring Boot 1.4.0, Spring Boot Admin 1.4.1, and build with Gradle.

I intercepted the requests with netcat and indeed, this is what one of the other apps sends:

```
POST /api/applications HTTP/1.1
Accept: application/json
Content-Type: application/json
User-Agent: Java/1.8.0_92
Host: localhost:7015
Connection: keep-alive
Content-Length: 218

{"managementUrl":"http://192.168.1.64:8080","healthUrl":"http://192.168.1.64:8080/health","serviceUrl":"http://192.168.1.64:8080","name":"distribs","id":null,"statusInfo":{"status":"UNKNOWN","timestamp":1472142902817}}
```

And this is what the app with netty sends:

```
POST http://localhost:7015/api/applications HTTP/1.1
Host: localhost
Connection: close
Accept: application/json
Content-Type: application/json

{"managementUrl":"http://192.168.1.64:8080","healthUrl":"http://192.168.1.64:8080/health","serviceUrl":"http://192.168.1.64:8080","name":"tx","id":null,"statusInfo":{"status":"UNKNOWN","timestamp":1472143151744}}
```

Maybe the problem is that the client is not sending `Content-Length`, or could it be the `keep-alive` property for the connection? Anyway, I don't know why the mere existence of netty on the classpath causes this difference; probably some Spring component detects it and uses it instead of whatever is used when netty's not available.

Unfortunately, my app needs to use netty for other stuff. Is there a way to disable netty usage on the spring boot admin client?

**Comment by joshiste** [comment] 2016-08-26 12:27
duplicate of #248

**Closed by joshiste** 2016-08-26 12:27 UTC
Labels: duplicate
