### ISSUE TITLE
SBA Client uses bad configured RestTemplate when registering

### ISSUE THREAD

**Issue by mohnid** [codecentric/spring-boot-admin#248] opened 2016-08-11 16:56 UTC
I try to integrate this great tool for our new projects, but as we switched to log4j2 collecting logs with gelf I found a issue. If log4j-gelf is in the classpath, the client can not register.

simple spring boot client for testing is attached...

[spring-boot-admin-client-test.zip](https://github.com/codecentric/spring-boot-admin/files/413726/spring-boot-admin-client-test.zip)

Any ideas ?

**Comment by mohnid** [comment] 2016-08-12 06:54
Follow up: 
This is related to the use of the RestTemplateBuilder, if netty (log4j-gelf -> gelfclient -> nettty dependency) ist in the classpath a Netty4ClientHttpRequest will be used.
Now I need to find out how to customize the Builder....

**Comment by joshiste** [comment] 2016-08-12 07:14
This is maye caused by the error fixed with #247 introduces in 1.4.x. Since there is no change in the REST-api you could try to use 1.3.6 just for the client....

**Comment by mohnid** [comment] 2016-08-12 07:38
I fixed it using a defined RequestFactory in the registrator...

        builder = builder.requestFactory(SimpleClientHttpRequestFactory.class);

But this is maybe not the correct way to go.
The 1.36 client works fine

**Closed** 2016-08-26 12:33 UTC
Labels: bug
