### ISSUE TITLE
webpack -p throws a exception

### ISSUE THREAD

**Issue by chinahappyking** [codecentric/spring-boot-admin#369] opened 2016-12-26 07:15 UTC
Could you please support webpack? i.e.:

    ERROR in ./core/img/platform-spring-boot.png
    Module parse failed: D:\spring-boot-admin\spring-boot-admin-server-ui\core\img\platform-spring-boot.png Unexpected character '�' (1:0)
    You may need an appropriate loader to handle this file type.
    SyntaxError: Unexpected character '�' (1:0)
        at Parser.pp$4.raise (D:\spring-boot-admin\spring-boot-admin-server-ui\node_modules\webpack\node_modules\acorn\dist\acorn.js:2221:15)
        at Parser.pp$7.getTokenFromCode (D:\spring-boot-admin\spring-boot-admin-server-ui\node_modules\webpack\node_modules\acorn\dist\acorn.js:2756:10)
        at Parser.pp$7.readToken (D:\spring-boot-admin\spring-boot-admin-server-ui\node_modules\webpack\node_modules\acorn\dist\acorn.js:2477:17)
        at Parser.pp$7.nextToken (D:\spring-boot-admin\spring-boot-admin-server-ui\node_modules\webpack\node_modules\acorn\dist\acorn.js:2468:15)
        at Parser.parse (D:\spring-boot-admin\spring-boot-admin-server-ui\node_modules\webpack\node_modules\acorn\dist\acorn.js:515:10)
        at Object.parse (D:\spring-boot-admin\spring-boot-admin-server-ui\node_modules\webpack\node_modules\acorn\dist\acorn.js:3098:39)
        at Parser.parse (D:\spring-boot-admin\spring-boot-admin-server-ui\node_modules\webpack\lib\Parser.js:902:15)
        at DependenciesBlock.<anonymous> (D:\spring-boot-admin\spring-boot-admin-server-ui\node_modules\webpack\lib\NormalModule.js:104:16)
        at DependenciesBlock.onModuleBuild (D:\spring-boot-admin\spring-boot-admin-server-ui\node_modules\webpack-core\lib\NormalModuleMixin.js:310:10)
        at nextLoader (D:\spring-boot-admin\spring-boot-admin-server-ui\node_modules\webpack-core\lib\NormalModuleMixin.js:275:25)
        at D:\spring-boot-admin\spring-boot-admin-server-ui\node_modules\webpack-core\lib\NormalModuleMixin.js:259:5
        at Storage.provide (D:\spring-boot-admin\spring-boot-admin-server-ui\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:52:20)
        at CachedInputFileSystem.readFile (D:\spring-boot-admin\spring-boot-admin-server-ui\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:140:24)
        at DependenciesBlock.onLoadPitchDone (D:\spring-boot-admin\spring-boot-admin-server-ui\node_modules\webpack-core\lib\NormalModuleMixin.js:255:7)
        at DependenciesBlock.loadPitch (D:\spring-boot-admin\spring-boot-admin-server-ui\node_modules\webpack-core\lib\NormalModuleMixin.js:182:27)
        at DependenciesBlock.doBuild (D:\spring-boot-admin\spring-boot-admin-server-ui\node_modules\webpack-core\lib\NormalModuleMixin.js:241:4)
        at DependenciesBlock.build (D:\spring-boot-admin\spring-boot-admin-server-ui\node_modules\webpack\lib\NormalModule.js:84:14)
        at Compilation.buildModule (D:\spring-boot-admin\spring-boot-admin-server-ui\node_modules\webpack\lib\Compilation.js:126:9)
        at D:\spring-boot-admin\spring-boot-admin-server-ui\node_modules\webpack\lib\Compilation.js:309:10
        at D:\spring-boot-admin\spring-boot-admin-server-ui\node_modules\webpack\lib\NormalModuleFactory.js:58:13
        at NormalModuleFactory.applyPluginsAsyncWaterfall (D:\spring-boot-admin\spring-boot-admin-server-ui\node_modules\tapable\lib\Tapable.js:75:69)
        at onDoneResolving (D:\spring-boot-admin\spring-boot-admin-server-ui\node_modules\webpack\lib\NormalModuleFactory.js:38:11)
        at onDoneResolving (D:\spring-boot-admin\spring-boot-admin-server-ui\node_modules\webpack\lib\NormalModuleFactory.js:121:6)
        at D:\spring-boot-admin\spring-boot-admin-server-ui\node_modules\webpack\lib\NormalModuleFactory.js:116:7
        at D:\spring-boot-admin\spring-boot-admin-server-ui\node_modules\async\lib\async.js:726:13
        at D:\spring-boot-admin\spring-boot-admin-server-ui\node_modules\async\lib\async.js:52:16
        at async.forEachOf.async.eachOf (D:\spring-boot-admin\spring-boot-admin-server-ui\node_modules\async\lib\async.js:236:30)
        at _parallel (D:\spring-boot-admin\spring-boot-admin-server-ui\node_modules\async\lib\async.js:717:9)
        at Object.async.parallel (D:\spring-boot-admin\spring-boot-admin-server-ui\node_modules\async\lib\async.js:731:9)
        at D:\spring-boot-admin\spring-boot-admin-server-ui\node_modules\webpack\lib\NormalModuleFactory.js:109:12
     @ ./~/.0.25.0@css-loader?-minimize!./core/css/core.css 6:2767-2809

    ERROR in ./third-party/googlefonts/VarelaRound-Regular.ttf
    Module parse failed: D:\spring-boot-admin\spring-boot-admin-server-ui\third-party\googlefonts\VarelaRound-Regular.ttf Unexpected character '

**Comment by chinahappyking** [comment] 2016-12-26 07:16
add webpack.config.js

'use strict';

var Webpack = require('webpack'),
  NgAnnotatePlugin = require('ng-annotate-webpack-plugin'),
  CopyWebpackPlugin = require('copy-webpack-plugin'),
  CleanWebpackPlugin = require('clean-webpack-plugin'),
  ExtractTextPlugin = require('extract-text-webpack-plugin'),
  path = require('path'),
  glob = require('glob');

var DIST = path.resolve(__dirname, 'target/dist');
var ROOT = __dirname;
var isDevServer = path.basename(require.main.filename) === 'webpack-dev-server.js';

var allModules = glob.sync(ROOT + '/modules/*/module.js').map(function (file) {
  var name = /modules\/([^\/]+)\/module\.js/.exec(file)[1];
  return {
    name: name,
    bundle: name + '/module',
    entry: './' + path.relative(ROOT, file),
    outputPath: name + '/'
  };
});

var getEntries = function (modules) {
  var entries = {
    'core': './core/core.js',
    'dependencies.js': ['jquery', 'bootstrap', 'angular', 'angular-resource', 'angular-ui-router']
  };
  modules.forEach(function (module) {
    entries[module.bundle] = module.entry;
  });
  return entries;
};

var ConcatSource = require('webpack-sources').ConcatSource;
var ModuleConcatPlugin = function (files) {
  this.files = files;
};
ModuleConcatPlugin.prototype.apply = function (compiler) {
  var self = this;
  compiler.plugin('emit', function (compilation, done) {
    self.files.forEach(function (file) {
      var newSource = new ConcatSource();
      Object.keys(compilation.assets).forEach(function (asset) {
        if (file.test.test(asset)) {
          newSource.add(compilation.assets[asset]);
          newSource.add(file.delimiter);
        }
      });
      if (newSource.children.length > 0) {
        compilation.assets[file.filename] = newSource;
      }
    });
    done();
  });
};

module.exports = {
  context: ROOT,
  entry: getEntries(allModules),
  output: {
    path: DIST,
    filename: '[name].js'
  },
  resolve: {
    alias: {
      bootstrap: path.resolve(ROOT, 'third-party/bootstrap/js/bootstrap.js'),
      'bootstrap.css': path.resolve(ROOT, 'third-party/bootstrap/css/bootstrap.css'),
      'bootstrap-responsive.css': path.resolve(ROOT, 'third-party/bootstrap/css/bootstrap-responsive.css'),
      'googlefonts.css': path.resolve(ROOT, 'third-party/googlefonts/googlefonts.css'),
      jolokia: path.resolve(ROOT, 'modules/applications-jmx/third-party/jolokia.js')
    }
  },
  module: {
    preLoaders: [{
      test: /\.js$/,
      loader: 'eslint',
      exclude: [/node_modules/, /third-party/]
    }],
    loaders: [
      {
        test: /^jolokia$/,
        loader: 'imports?$=jquery'
      }, {
        test: /\.js$/,
        exclude: [/node_modules/, /third-party/],
        loader: 'ng-annotate'
      }, {
        test: /\.tpl\.html$/,
        loader: 'raw'
      }, {
        test: /\.css(\?.*)?$/,
        loader: 'style!css'
      }, {
        test: /\.(jpg|png|gif|eot|svg|ttf|woff(2)?)(\?.*)?$/,
        include: /\/(third-party|node_modules)\//,
        loader: 'file',
        query: {
          name: 'third-party/[2]',
          regExp: '(third-party|node_modules)/(.+)'
        }
      }, {
        test: /\.(jpg|png|gif)$/,
        include: /\/(core|modules)\//,
        loader: 'file',
        query: {
          name: '[2]',
          regExp: '(core|modules)/(.+)$'
        }
      }]
  },
  plugins: [
    new CleanWebpackPlugin([DIST]),
    new ExtractTextPlugin('[name].css'),
    new Webpack.ProvidePlugin({
      'window.jQuery': 'jquery'
    }),
    new NgAnnotatePlugin({
      add: true
    }),
    new Webpack.optimize.CommonsChunkPlugin({
      name: 'dependencies.js',
      filename: 'dependencies.js'
    }),
    new CopyWebpackPlugin([{
      from: '**/*.html',
      context: 'core/'
    }, {
      from: '**/*.html',
      context: 'modules/'
    }],
      { ignore: ['*.tpl.html'] })
  ].concat(!isDevServer ? [] : new ModuleConcatPlugin([
    {
      filename: 'all-modules.js',
      test: /module\.js/,
      delimiter: ';\n'
    }, {
      filename: 'all-modules.css',
      test: /module\.css/,
      delimiter: '\n'
    }
  ])),
  devServer: {
    proxy: [{
      context: '/api',
      target: 'http://localhost:8080',
      secure: false
    }]
  },
  node: {
    fs: 'empty'
  }
};

**Comment by joshiste** [comment] 2016-12-26 16:03
Which branch are you using? Looks like a duplicate of #363 which has been recently fixed on the master branch.

**Closed by joshiste** 2016-12-26 16:03 UTC

**Comment by chinahappyking** [comment] 2016-12-27 10:05
with that change the building the UI is successful, thanks @joshiste
