### ISSUE TITLE
Periodical HttpMediaTypeNotAcceptable exceptions saturating the logs

### ISSUE THREAD

**Issue by Daerthox** [codecentric/spring-boot-admin#289] opened 2016-10-02 14:17 UTC
We are developing micro-services in Java using spring boot. We were interested in a way to change the logging level of each of our loggers at run-time. I have integrated admin UI to one of our services. The service is acting as both the sever and the client, monitoring itself. We really are mostly interested in changing the logging level at run time, so we would rather not have separate server for that purpose.

Even though the UI is working fine, I noticed that there is an error coming up periodically, about twice a minute, and saturating the logs. It comes soon after I hit the admin UI route for the service and is a HttpMediaTypeNotAcceptable exception that displays the message "Could not find an acceptable representation". It seems to be coming from the "/api/journal;client=0:0:0:0:0:0:0:1" route.

Could you shed some light on this issue, as I am in the dark? I don't know what is causing this issue and how to stop it.

**Comment by joshiste** [comment] 2016-10-02 16:14
The UI queries the `/api/journal` for the desktop notifications. Since you're adding the sba server to your application I guess there is a conflict with it's ContentType configurations..,

You need to provide 1) a stacktrace and 2) sample code to reproduce the error.

```java
	@RequestMapping(path = "/api/journal", produces = "text/event-stream")
	public SseEmitter getJournalEvents() {
...
```

**Comment by Daerthox** [comment] 2016-10-03 16:07
You can see the result of the console online here: https://justpaste.it/yyak
I will provide a gist with a sample code later. I noticed that the exception manifests itself when I hit the UI from two different tabs.

**Comment by joshiste** [comment] 2016-10-05 16:41
@Daerthox sorry but the gist is of no use. Can you provide the sample project as zip?

**Comment by joshiste** [comment] 2016-10-13 04:24
@Daerthox After 7 days still waiting on a response. Does the problem still remain? Please provide the needed info in the next days or I'll close the issue.

> sorry but the gist is of no use. Can you provide the sample project as zip?

**Comment by rfelgent** [comment] 2016-10-13 14:50
I was wrong, SBAP gives strange errors:

2016-10-13 16:31:00.189 ERROR 12418 --- [updateTask1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task.

java.lang.NullPointerException: null
	at de.codecentric.boot.admin.notify.filter.FilteringNotifier.notify(FilteringNotifier.java:52)
	at de.codecentric.boot.admin.notify.RemindingNotifier.notify(RemindingNotifier.java:44)
	at de.codecentric.boot.admin.notify.NotifierListener.onClientApplicationEvent(NotifierListener.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:226)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:143)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:105)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:166)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:382)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:349)
	at de.codecentric.boot.admin.registry.StatusUpdater.updateStatus(StatusUpdater.java:68)
	at de.codecentric.boot.admin.registry.StatusUpdater.updateStatusForAllApplications(StatusUpdater.java:55)
	at de.codecentric.boot.admin.registry.StatusUpdateApplicationListener$1.run(StatusUpdateApplicationListener.java:54)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

2016-10-13 16:31:10.188 ERROR 12418 --- [updateTask1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task.

java.lang.NullPointerException: null
	at de.codecentric.boot.admin.notify.filter.FilteringNotifier.notify(FilteringNotifier.java:52)
	at de.codecentric.boot.admin.notify.RemindingNotifier.notify(RemindingNotifier.java:44)
	at de.codecentric.boot.admin.notify.NotifierListener.onClientApplicationEvent(NotifierListener.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:226)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:143)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:105)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:166)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:382)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:349)
	at de.codecentric.boot.admin.registry.StatusUpdater.updateStatus(StatusUpdater.java:68)
	at de.codecentric.boot.admin.registry.StatusUpdater.updateStatusForAllApplications(StatusUpdater.java:55)
	at de.codecentric.boot.admin.registry.StatusUpdateApplicationListener$1.run(StatusUpdateApplicationListener.java:54)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by rfelgent** [comment] 2016-10-13 14:56
Error still persists

**Comment by Daerthox** [comment] 2016-10-18 19:59
There you go http://tinyurl.com/hg44ceo
However I now believe it was just a network or proxy issue. I recently tried it on another network and found no error.

**Comment by joshiste** [comment] 2016-10-19 04:20
I'm closing this issue, when you can't reproduce it yourself.

**Closed by joshiste** 2016-10-19 04:20 UTC
