### ISSUE TITLE
spring-boot-admin server starts but shortly starts to log java.io.IOException: Too many open files

### ISSUE THREAD

**Issue by jhartotr** [codecentric/spring-boot-admin#1478] opened 2020-07-20 10:27 UTC
After upgrading to spring boot v2.3.1.RELEASE and spring-admin version 2.2.3, starting the admin server works find however shortly following exception starts to get logged:

```
2020-07-20 10:19:10.903 ERROR 32017 --- [o-8080-Acceptor] org.apache.tomcat.util.net.Acceptor      : Socket accept failed

java.io.IOException: Too many open files
	at java.base/sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method) ~[na:na]
	at java.base/sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:533) ~[na:na]
	at java.base/sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:285) ~[na:na]
	at org.apache.tomcat.util.net.NioEndpoint.serverSocketAccept(NioEndpoint.java:469) ~[tomcat-embed-core-9.0.36.jar!/:9.0.36]
	at org.apache.tomcat.util.net.NioEndpoint.serverSocketAccept(NioEndpoint.java:71) ~[tomcat-embed-core-9.0.36.jar!/:9.0.36]
	at org.apache.tomcat.util.net.Acceptor.run(Acceptor.java:95) ~[tomcat-embed-core-9.0.36.jar!/:9.0.36]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
```

After this the admin UI doesn't show the metrics properly.

**Comment by joshiste** [comment] 2020-07-20 10:29
duplicate of #1459

**Closed by joshiste** 2020-07-20 10:29 UTC
Labels: bug, waiting-for-triage
