### ISSUE TITLE
spring-boot-admin在spring-cloud-consul-discovery使用v3.0.0+时，无法获取metadata

### ISSUE THREAD

**Issue by lyguoguo** [codecentric/spring-boot-admin#2076] opened 2022-07-27 12:50 UTC
背景 springboot 2.6.8 spring-cloud 2021.0.1 spring-cloud-alibaba 2021.0.1.0 服务采用consul作为注册中心
问题
spring-cloud 2021.0.1 中 spring-cloud-starter-consul-discovery 3.1.0 
ConsulDiscoveryClient.addInstancesToList()在该版本中getMetadata()由
<img width="867" alt="1658914512947_C6312067-94A0-4bec-90B1-8B161899BFD5" src="https://user-images.githubusercontent.com/47592626/181250135-ac820b5d-85af-4bc9-b11e-490f2490c99d.png">
转变为
<img width="431" alt="1658914563285_DB881498-E030-4a3e-B9CF-BBA468680066" src="https://user-images.githubusercontent.com/47592626/181250167-047e94ff-c6fe-47eb-808b-35ce1f1bfa85.png">
，新版本不支持从tag读取metadata信息，必须注册meta。
但consul metadata注册不支持“management.context-path”这种key包含“.”的注册，会报异常“Bad request: Invalid Service Meta: Couldn't load metadata pair ('management.context-path', 'xxx'): Key contains invalid characters”
因此导致需要指定“management.context-path”或“health.path”等的服务无法正确获取metadata，从而导致服务监控异常。

**Comment by erikpetzold** [comment] 2022-07-29 06:02
> Background 
springboot 2.6.8 
spring-cloud 2021.0.1 
spring-cloud-alibaba 2021.0.1.0 
The service uses consul as the registry
>
>question
spring-cloud-starter-consul-discovery 3.1.0 in spring-cloud 2021.0.1
ConsulDiscoveryClient.addInstancesToList() in this version getMetadata() by
>
>image
>
>Into
>
>image
>
>, the new version does not support reading metadata information from tags, meta must be registered.
>
>However, the registration of consul metadata does not support the registration of "management.context-path" whose key contains ".", and an exception will be reported "Bad request: Invalid Service Meta: Couldn't load metadata pair ('management.context-path', ' xxx'): Key contains invalid characters”
>
>As a result, services that need to specify "management.context-path" or "health.path" cannot obtain metadata correctly, resulting in service monitoring exceptions.

**Comment by erikpetzold** [comment] 2022-07-29 06:31
Hi @lyguoguo 

we have understood that the old version of spring-cloud-consul-discovery contained the code from the first screenshot. It was reading metadata from tags.
The second screenshot shows the new version which does not read from tags anymore.

So now you tried to register metadata yourself. How did you do that?

The issue seems like a duplicate of #1737 where some workarounds are linked. Sadly no one fixed the base problem yet.

**Comment by lyguoguo** [comment] 2022-07-29 07:44
> Hi @lyguoguo
> 
> we have understood that the old version of spring-cloud-consul-discovery contained the code from the first screenshot. It was reading metadata from tags. The second screenshot shows the new version which does not read from tags anymore.
> 
> So now you tried to register metadata yourself. How did you do that?
> 
> The issue seems like a duplicate of #1737 where some workarounds are linked. Sadly no one fixed the base problem yet.

so  sad

**Comment by lyguoguo** [comment] 2022-07-29 07:45
The issue seems like a duplicate of https://github.com/codecentric/spring-boot-admin/issues/1737 where some workarounds are linked.

**Closed** 2022-07-29 07:44 UTC
Labels: bug

**Comment by lyguoguo** [comment] 2022-07-29 07:50
We have verified that Nacos supports metadata registration in the form of management.context-path. Consul can't. It's too sad.

**Comment by erikpetzold** [comment] 2022-08-15 07:58
hi @lyguoguo , have you seen that #1737 has been fixed now? You can now provide the properties with dash instead of dot, so consul will accept them
