### ISSUE TITLE
httptraces causes out-of-memory in browser

### ISSUE THREAD

**Issue by super-ning** [codecentric/spring-boot-admin#1040] opened 2018-12-18 09:10 UTC
### http-trace click view  paused before potential out-of-memory crash bug
collapse

```xml
<dependencies>
        <dependency>
            <groupId>de.codecentric</groupId>
            <artifactId>spring-boot-admin-starter-server</artifactId>
            <version>2.0.1</version>
        </dependency>
        <dependency>
            <groupId>de.codecentric</groupId>
            <artifactId>spring-boot-admin-server-ui</artifactId>
            <version>2.0.1</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-mail</artifactId>
        </dependency>
    </dependencies>
```

**Comment by benjefferies** [comment] 2018-12-18 12:14
We've also seen this on 2.0.2

**Comment by joshiste** [comment] 2018-12-18 16:46
please look at your responses. It looks like a duplicate of #861 to me.

**Comment by klopfdreh** [comment] 2019-02-14 13:29
Hi,

we also have this issue (SBAdmin 2.0.2). It is very hard to trace this down, but I tried it with the developer console of chrome. Here is a screenshot were the script stops:

![screen shot 2019-02-14 at 2 22 01 pm](https://user-images.githubusercontent.com/980773/52789593-8d7aaa00-3064-11e9-85f1-c07c8bb0e450.png)

Note: We have other micro service registered on the same SBAdmin and the http trace for those are working fine. I think this issue occurs if there are a lot of http requests are coming in.

Hope this helps.

**Comment by klopfdreh** [comment] 2019-02-15 04:47
@joshiste would you be so kind and have a look at this / reopen the ticket?

**Comment by joshiste** [comment] 2019-02-15 07:23
@klopfdreh in the past this error was mostly caused by custom json format of the httptraces endpoint can you show me the content of your response?

**Comment by super-ning** [comment] 2019-02-15 08:57
@joshiste I have tried all kinds of json formats, but it is not useless.

**Comment by klopfdreh** [comment] 2019-02-15 09:06
@joshiste I can't hand over the JSON, because it is client and user related.

However I was able to access the JSON by calling:

https://domain-name/sbadmin/instances/<instanceid>/actuator/httptrace.

I just looked through the code and saw a change regarding the Jackson2ObjectMapperBuilder.

```java
    @Bean
    public Jackson2ObjectMapperBuilder jacksonMapperBuilder() {
        Jackson2ObjectMapperBuilder builder = new Jackson2ObjectMapperBuilder();

        builder.deserializerByType(LocalDateTime.class, LocalDateTimeZoneIgnoringDeserializer.INSTANCE);
        builder.featuresToDisable(DeserializationFeature.ADJUST_DATES_TO_CONTEXT_TIME_ZONE);

        return builder;
    }
```

Does this also affects the actuator endpoints or do they use a separate Jackson2ObjectMapperBuilder bean?

**Comment by klopfdreh** [comment] 2019-03-01 08:36
Anything I can provide further on to move this ticket forward / get this issue fixed?

**Comment by joshiste** [comment] 2019-03-01 09:12
Sorry, somehow I missed your last response.
 
> Does this also affects the actuator endpoints or do they use a separate Jackson2ObjectMapperBuilder bean?

Yes it does affect the actuator endpoints. See https://github.com/spring-projects/spring-boot/issues/12951

**Comment by klopfdreh** [comment] 2019-03-01 10:19
Do you know if this could lead to this issues? I don’t know on how to setup a scenario to test this - are there any unit / frontend tests to check this is out?

**Comment by klopfdreh** [comment] 2019-03-02 04:17
Thanks! I am going to try it out and find the bug - meanwhile can we reopen the issue?

**Comment by klopfdreh** [comment] 2019-03-04 09:03
Hi @joshiste,

I was able to debug the JS code from within chrome and the JSON and all data seems to be fine. I set a break point **before** the "for"-loop and was able to run through the first two chartData iterations where the buckets are pushed. When I release the break point the issue with the out-of-memory crash is occurring.

So my assumption is that this is simply an issue of to many **traces** for a specific time period which are causing an out-of-memory exception. I guess the markup is growing to much. (The one within the template)

My suggestion would be to introduce a limit for those traces which is configurable and use
```javascript
traces = myarray.slice(0,<limit>);
```
to shrink down the array if it hits that limit.

Also I would suggest to not show all traces for the time period of viewing but recalculate the time period according to the amount of traces returned by the slice call.

This way the shown time would not increase infinite, but move based on the traces.

Here is a screenshot of my first successful run through:

<img width="1410" alt="screen shot 2019-03-04 at 9 38 49 am" src="https://user-images.githubusercontent.com/980773/53721531-bc19c280-3e63-11e9-9301-3896e060091c.png">

**Comment by joshiste** [comment] 2019-03-04 15:44
Did you

**Comment by klopfdreh** [comment] 2019-03-06 07:52
@joshiste - do you require some more feedback or is this something which helps out with this issue?

**Comment by joshiste** [comment] 2019-03-06 10:16
@klopfdreh do you think you could do a PR on this?

**Comment by klopfdreh** [comment] 2019-03-06 11:01
@joshiste yes of course, but it is going to take some time until I can provide it because a lot of releases at work at the moment.

So one suggestion would be to make the limit field available within the same page of the httptrace - so that you can change the value on the fly - WDYT?

**Comment by klopfdreh** [comment] 2019-03-06 11:23
Oh it was rather easy to make those changes - do I have permisstion to create branches / perform a PR in this case?

**Comment by klopfdreh** [comment] 2019-03-06 12:01
Ok, I think the PR is ready for review, now.

**Comment by joshiste** [comment] 2019-03-06 19:28
Did you test that the changes prevents the out-of-memory

**Comment by klopfdreh** [comment] 2019-03-06 20:11
For me it does but slows down a lot so I am not sure about the correct setting for the limit. What do you think we should make as default? 500?

I have no idea in this case.

**Comment by klopfdreh** [comment] 2019-03-06 20:16
For me it does but slows down because 1000 is a big value for this and of course a lot of markup.

What do you think we should set as a default limit? 500?

Please also run it and see if there are any errors or I missed something (regarding filter / selection) - within this short time I couldn‘t test all functionalities working together without issues.

**Comment by klopfdreh** [comment] 2019-03-06 20:17
For me it does but slows down because 1000 is a big value for this and of course a lot of markup.

What do you think we should set as a default limit? 500?

Please also run it and see if there are any errors or I missed something (regarding filter / selection) - within this short time I couldn‘t test all functionalities working together without issues.

**Comment by klopfdreh** [comment] 2019-03-06 20:20
@super-ning - can you also test those changes and report if this is working for you?

**Comment by klopfdreh** [comment] 2019-03-06 20:32
I also saw that there is a logic according to concat traces - so my changes may initially work but lead to some errors if the next traces are retrieved with fetchHttptrace. Also it takes only the first 1000, but the order of the traces might be not correct, because they are sorted after the slice - also I guess we have to take the last 1000 not the first after the comparison right?

https://github.com/klopfdreh/spring-boot-admin/blob/b69728e89f3d31e6c0477fa075493c4a8b16b3cd/spring-boot-admin-server-ui/src/main/frontend/views/instances/httptrace/index.vue#L200

**Comment by joshiste** [comment] 2019-03-06 20:38
Yep, I already spotted it and will take care of it.

**Comment by klopfdreh** [comment] 2019-03-06 20:40
Thanks a lot! 👍 

I would suggest to do something like

traces.slice(slice.length-this.limit,slice.length) if traces.length is bigger than the limit after the sorting

**Comment by joshiste** [comment] 2019-03-06 20:46
closed with acfa5b73f87363ac443d90398698c30886b306ae

**Closed by joshiste** 2019-03-06 20:46 UTC
Labels: bug, server-ui

**Comment by joshiste** [comment] 2019-03-06 20:50
> For me it does but slows down because 1000 is a big value for this and of course a lot of markup.

Yeah, we should use something like vue-virtual-scroller so that non visible entries are not included it the first render...

**Comment by klopfdreh** [comment] 2019-03-07 06:22
Thanks a lot for your time! 👍

**Comment by klopfdreh** [comment] 2019-03-08 09:08
Just want to link an already closed ticket, because I think it could belong to this one as well:

#1053
