### ISSUE TITLE
Failing to load UI modules

### ISSUE THREAD

**Issue by chriswhitcombe** [codecentric/spring-boot-admin#326] opened 2016-11-10 16:42 UTC
I've updated my pom to bring in the hystrix and activiti ui modules and added the following line to my config.

spring.boot.admin.routes.endpoints: env,metrics,trace,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,hystrix.stream,activiti

However when i check the UI only the following modules have loaded: 
sba-about
sba-applications
sba-applications-details
sba-applications-environment
sba-applications-flyway
sba-applications-heapdump
sba-applications-jmx
sba-applications-liquibase
sba-applications-logfile
sba-applications-logging
sba-applications-metrics
sba-applications-threads
sba-applications-trace
sba-core
sba-events

But if i look in the logs i can clearly see this:

2016-11-10 16:09:57.382  INFO 1172 --- [nio-8887-exec-1] o.s.c.n.zuul.web.ZuulHandlerMapping      : Mapped URL path [/api/applications/346c1283/hystrix.stream/**] onto handler of type [class de.codecentric.boot.admin.zuul.OptionsDispatchingZuulController]
2016-11-10 16:09:57.382  INFO 1172 --- [nio-8887-exec-1] o.s.c.n.zuul.web.ZuulHandlerMapping      : Mapped URL path [/api/applications/346c1283/activiti/**] onto handler of type [class de.codecentric.boot.admin.zuul.OptionsDispatchingZuulController]

Ive also packaged a jar with the spring boot plugin and can see that they are present in the libs folder, so they are definitely included.

Do you have a sample project running with them in? Without knowing where or how they will appear in the UI its pretty hard to debug things further?

**Comment by joshiste** [comment] 2016-11-10 17:27
The eureka example includes the hystrix module. The `spring.boot.admin.routes.endpoints` property just reconfigures the zuul proxy. The module should be listed in the about page. If not I guess the jars are somehow not on your classpath...

The admin server looks for all `classpath*:/META-INF/spring-boot-admin-server-ui/*/module.js` files and serves them concatenated as `all-modules.js`. 
Since I miserably failed in adding log statements in the right places you could debug into `ResourcePatternResolvingResourceResolver` and see which files are found on the classpath....

**Comment by joshiste** [comment] 2016-11-16 21:26
Any news on this from your side? can I close the issue?
You could update to 1.4.4 and set the logger for `ResourcePatternResolvingResourceResolver` to debug and see which modules got resolved.
Otherwise you need to provide a reproducible sample for me...

**Comment by joshiste** [comment] 2016-11-20 14:25
closing due to missing feedback

**Closed by joshiste** 2016-11-20 14:25 UTC
Labels: waiting-for-feedback
