### ISSUE TITLE
allow credentials sharing through discovery metadata

### ISSUE THREAD

**Issue by whboyd** [codecentric/spring-boot-admin#375] opened 2017-01-03 18:33 UTC
It would be really nice if, when using discovery, spring-boot-admin could discover credentials needed to access metrics endpoints by having the client app publish the credentials to eureka metadata.

The specific use case I have in mind would be to let the client app randomize a metrics password at startup, report those credentials to eureka, and have spring-boot-admin discover those credentials and use them to access the client app's actuator endpoints.

**Comment by joshiste** [comment] 2017-01-03 21:35
Duplicate of #359

**Closed** 2017-01-03 21:35 UTC
