### ISSUE TITLE
Issue with the turbine dashboard view in Spring Boot Admin

### ISSUE THREAD

**Issue by surajrrao** [codecentric/spring-boot-admin#351] opened 2016-12-05 19:43 UTC
Getting below error message

Unable to connect to Command Metric Stream 'api/turbine/stream?cluster=REPORTS'.
Error: {"isTrusted":true}

**Comment by herder** [comment] 2016-12-05 20:18
This is because the embedded Zuul proxy which proxies the `/turbine.stream` endpoint closes the stream after a short time.
I suspect that the easiest way would be add an `@EnableTurbine` in the config and use the `/turbine.stream` endpoint directly instead, since that works fine.

**Comment by joshiste** [comment] 2016-12-06 06:19
Are the graphs showing up anyway despite the error message?

**Comment by herder** [comment] 2016-12-06 16:17
Yes, they show up, then stop when the stream closes from Zuul.
I don't think it seems Zuul can handle event streams very well, so imho it would probably be better to go against the turbine.stream directly.

**Comment by joshiste** [comment] 2016-12-23 21:15
> I don't think it seems Zuul can handle event streams very well, so imho it would probably be better to go against the turbine.stream directly.

Another solution would be to copy and modify the ProxyServlet from the original hystrix-dashboard

**Comment by joshiste** [comment] 2016-12-23 22:27
I currently can't reproduce the issue...

Yes the current (offical) Spring Cloud Zuul filters have problems with long running requests. But I included a patched filter with the changes from https://github.com/spring-cloud/spring-cloud-netflix/pull/1372.

So any hints on how to reproduce the issue?

**Comment by joshiste** [comment] 2017-01-05 06:08
Any feedback on this? Otherwise I close the issue in 2 days...

**Comment by herder** [comment] 2017-01-05 06:32
> Any feedback on this? Otherwise I close the issue in 2 days...

Sorry, still on Christmas vacation here... :)
But I checked with 1.4.5, and everything seems to work fine now. So as far as I'm concerned, this issue can be closed.

**Comment by joshiste** [comment] 2017-01-06 21:29
Closed due to Missing Feedback.

**Closed by joshiste** 2017-01-06 21:29 UTC
Labels: bug, server, waiting-for-feedback

**Comment by heymysweetheart** [comment] 2017-01-17 08:40
@herder Hi I am using version `1.4.5` for `spring-boot-admin-server`, `spring-boot-admin-server-ui`, `spring-boot-admin-server-ui-hystrix`, `spring-boot-admin-server-ui-turbine`. From admin server, hystrix dashboard works fine. But for admin turbine UI, I still have the same error info like bellow:
![image](https://cloud.githubusercontent.com/assets/9413173/22013096/437adf84-dcd2-11e6-8524-598af8fa5373.png)

Also as you mentioned above I added an `spring-cloud-starter-turbine` dependency and `@EnableTurbine` in the config, and my application.yml config is:
```spring.boot.admin.turbine:
  clusters: default
  url: ${SPRING_BOOT_ADMIN_TURBINE_URL:http://localhost:8989/turbine.stream}
```

Above all done, I still have the topic error. 
Question is 

- What do you mean by 

> and use the /turbine.stream endpoint directly instead, since that works fine.

- Do I need to modify the `TurbineAutoConfiguration` and the front end js? 
- How to get this error fixed? 

Thank you!

**Comment by herder** [comment] 2017-01-17 20:18
> Above all done, I still have the topic error.
> Question is
> 
> What do you mean by
> and use the /turbine.stream endpoint directly instead, since that works fine.
> Do I need to modify the TurbineAutoConfiguration and the front end js?
> How to get this error fixed?
> Thank you!

Turns out I spoke too soon above: the patched Zuul filter also cuts the stream after a short while.
I can't see another way to fix this than using `@EnableTurbine` / `@EnableTurbineAmqp` and modifying `turbineCtrl.js` in the `spring-boot-admin-server-ui-turbine` module and using a locally built version instead. I was meaning to send a PR about this, but lots of stuff got in the way, as stuff often does...

But with the changes above, stuff works for me.

**Comment by herder** [comment] 2017-01-17 20:22
> But with the changes above, stuff works for me.

...i.e. change this line in `spring-boot-admin-server-ui-turbine/src/main/webpack/turbineCtrl.js`: 
`$scope.streamUrl = 'api/turbine/stream?cluster=' + $scope.selectedCluster;`

to this:
`$scope.streamUrl = 'turbine.stream?cluster=' + $scope.selectedCluster;`

**Comment by heymysweetheart** [comment] 2017-02-06 09:43
@herder Hi Herder, thank you so much for your clear explaination.

@joshiste Hi Johannes Edmeier, As there is still the issue for SBA 1.4.5,  do you already has a patch planned for future release? Thanks!

**Comment by joshiste** [comment] 2017-02-06 19:57
@heymysweetheart As I couldn't reproduce the error myself, it's hard to fix it.... Any hints on reproducing?

**Comment by litzuhsien** [comment] 2017-02-08 11:02
@heymysweetheart Please confirm the turbine.url is reachable from admin server, maybe your admin server port is not 8989...

**Comment by heymysweetheart** [comment] 2017-02-08 12:52
Hi @joshiste , @litzuhsien:


I tested the issue again, and reproduced the target issue. Here is what I did on my local macbook:

- Started a eureka server (docker instance).
- Started a service provider (docker instance).
- Started a service consumer (docker instance) which support hystrix.stream whose date is right.
- Started a turbine service (not docker instance) which can collect data of the consumer in step three.
- Started SBA (not docker instance) locally, whose turbine configuration was right and the url could be reachable on my browser. (It seems not reachable as the issue shows, don't know why.)
![image](https://cloud.githubusercontent.com/assets/9413173/22737742/60ed7206-ee3f-11e6-9e0b-746ec08adcab.png)
 

1.  Admin server port is 8700
2. Consumer server port is 8090
3. Turbine server port is 8989
4. Admin config about turbine is: `"spring.boot.admin.turbine.url": "http://localhost:8989/turbine.stream"`
5. Version of dependencies of admin-server, admin-server-ui, admin-server-ui-turbine is the same: `1.4.5`

Anything I did wrong please let me know, and I would be really happy to test further.

**Comment by ferdiozdemircit** [comment] 2017-04-06 20:49
For guys coming in from Google, this is fixed in version Spring boot admin 1.4.6!

**Comment by javanan** [comment] 2017-06-13 07:30
@heymysweetheart   大哥，问题解决了吗? 遇到同样的问题 。哈哈

**Comment by joshiste** [comment] 2017-06-13 08:32
@javanan english please, so that everybody can participate.

**Comment by javanan** [comment] 2017-06-13 08:38
@janoscc

 Ha-ha

Thank you. My question has been settled

```
  boot:
    admin:
      routes:
        endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
      turbine:
        clusters: default
        location: ss-service
```

These configurations I originally configured in remote windows

But admin reminds me that I can't find turbine serviceid

Finally, I'll configure it in the bootstrap.yml under the SBA service

**Comment by NeilZZ** [comment] 2017-06-16 07:51
@janoscc @joshiste 
hi, I have the same problem by i just using spring boot admin with Turbine. 
but my case is that:
while using security , this url api/turbine/stream?cluster=default, it will ask me to set the username and password.  but i have set the properties like security.ignored=/api/** . why it still can not ignore it .
but , while disable the security part. all work!

**Comment by addozhang** [comment] 2018-07-21 06:22
We are using 1.5.7 SBA which adds a `TurbineRouteLocator` to proxy `api/turbine/clusters` request to `turbine.stream` via zuul. But as we know zuul 1.x not supporting SSE and `turbine.stream` is just a SSE one. Zuul's `SimpleHostRoutingFilter` holds a connection pool and `maxPerRouteConnections` defaults to 20. Zuul never releases the connection to `turbine.stream`.

So we try to add one option for SBA to use `turbine.stream` directly and SBA will perceive client (such as brower) closing connection.
