### ISSUE TITLE
broken links /log and /heapdump when behind a webserver proxy

### ISSUE THREAD

**Issue by rfelgent** [codecentric/spring-boot-admin#269] opened 2016-09-13 09:02 UTC
Hello,

I am running SBAP 1.4.1 behind an Apache proxy. The url is http://xxxxx.de/sbap/. The requests are proxied correctly to the SPAP instance. Unfortunately the link generation for /log and /heapdump in the detail view of a service does not honor the "/sbap/".

is:  http://xxxxx.de/api/applications/c7dd10dc/logfile
desired: http://xxxxx.de/sbap/api/applications/c7dd10dc/logfile

Maybe it is a configuration fault on my side. But I do not know which flag to set...

**Comment by joshiste** [comment] 2016-09-13 16:45
For the logifle this is a duplicate of #263. For the heapdump we need a fix.

**Closed** 2016-09-13 16:45 UTC
Labels: bug
