### ISSUE TITLE
Progress bar refresh bug

### ISSUE THREAD

**Issue by leiguorui** [codecentric/spring-boot-admin#783] opened 2018-06-13 09:01 UTC
The filter of metrics does not seem to be able to update the progress bar.

**Comment by joshiste** [comment] 2018-06-13 10:47
Could you give a bit more explanation? As I don't understand what the issue is.
Which version of SBA you are referring to?

**Comment by joshiste** [comment] 2018-06-18 05:35
closing due to missing feedback.

**Closed by joshiste** 2018-06-18 05:35 UTC
Labels: waiting-for-feedback
