### ISSUE TITLE
Openshift: DiscoveryClient does not update applications

### ISSUE THREAD

**Issue by charlbrink** [codecentric/spring-boot-admin#643] opened 2018-02-08 14:53 UTC
Running Spring Boot Admin on Openshift with @EnableDiscoveryClient and the 
io.fabric8:spring-cloud-starter-kubernetes dependency added for service discovery and spring-cloud-starter-eureka excluded.

When the admin server starts up it finds the list of running applications and monitors their health status, but it does not know of any new instances that are started.

It would also be much more useful if it is aware of the number of expected replicas for each service as it keeps reporting an instance as down when a new replica was started on a different IP.

**Comment by joshiste** [comment] 2018-02-08 15:35
I don't have a Openshift/Kubernetes installation at hand so you need to track down the issue with me together. 
Please set the `de.codecentric.boot.admin.discovery.ApplicationDiscoveryListener` logger to `DEBUG` and add the output to this issue. 
Are you sure your SBA server is correctly connected to the registry / all you clients are?

> it keeps reporting an instance as down when a new replica was started on a different IP.

When the instance is removed from the service registry it also deregisters in SBA (when using discovery).
In case you are using the SBA client you can configure it to auto-deregister on shutdown.

**Comment by joshiste** [comment] 2018-02-08 21:35
Ok I guess the problem is that the `KubernetesDiscoveryClient` doesn't publish `HeartbeatEvent`s. So it's not directly a Spring Boot Admin issue....

**Comment by charlbrink** [comment] 2018-02-09 08:33
Thank you for the quick investigation and feedback.

**Comment by joshiste** [comment] 2018-02-14 06:11
The fabric8 project was moved to spring-cloud-incubator. I filed another issue: https://github.com/spring-cloud-incubator/spring-cloud-kubernetes/issues/150

**Comment by joshiste** [comment] 2018-03-05 15:44
I'm closing this issue as the spring-cloud-kubernetes project started working on this

**Closed by joshiste** 2018-03-05 15:44 UTC
Labels: bug, on hold, server
