### ISSUE TITLE
StringIndexOutOfBoundsException: String index out of range: -1

### ISSUE THREAD

**Issue by iwanzarembo** [codecentric/spring-boot-admin#245] opened 2016-08-05 11:55 UTC
I just followed the documentation [Getting Started -> 2.1 Setup Admin Server](http://codecentric.github.io/spring-boot-admin/1.3.4/#set-up-admin-server) and I started the [spring-boot-admin-sample](https://github.com/codecentric/spring-boot-admin/tree/master/spring-boot-admin-samples/spring-boot-admin-sample/) project. The problem is, if I start it and call http://localhost:8080/ then I get the following error:

> java.lang.StringIndexOutOfBoundsException: String index out of range: -1
> 	at java.lang.AbstractStringBuilder.replace(AbstractStringBuilder.java:824)
> 	at java.lang.StringBuilder.replace(StringBuilder.java:262)
> 	at de.codecentric.boot.admin.web.servlet.resource.ConcatenatingResourceResolver.buildDescription(ConcatenatingResourceResolver.java:93)
> 	at de.codecentric.boot.admin.web.servlet.resource.ConcatenatingResourceResolver.resolveResourceInternal(ConcatenatingResourceResolver.java:54)
> 	at org.springframework.web.servlet.resource.AbstractResourceResolver.resolveResource(AbstractResourceResolver.java:46)
> 	at org.springframework.web.servlet.resource.DefaultResourceResolverChain.resolveResource(DefaultResourceResolverChain.java:57)
> 	at de.codecentric.boot.admin.web.servlet.resource.ResourcePatternResolvingResourceResolver.resolveResourceInternal(ResourcePatternResolvingResourceResolver.java:53)
> 	at org.springframework.web.servlet.resource.AbstractResourceResolver.resolveResource(AbstractResourceResolver.java:46)

I did not change anything in the project and yes I do not have any applications registered yet. Could someone please check what is wrong?

**Comment by joshiste** [comment] 2016-08-05 13:51
The sample project is build against the snapshot version unless you have the sonatype snapshot configured you need to build the whole spring-boot-admin project first. And to do that you need to have nodejs and npm installed to be able to build the ui project....

**Comment by linux-china** [comment] 2016-08-08 05:24
java.lang.StringIndexOutOfBoundsException: String index out of range: -1

same problem for me.

**Comment by joshiste** [comment] 2016-08-08 06:05
The css files hasn't been packaged properly :cry:

**Comment by joshlong** [comment] 2016-08-08 06:42
i'm having the same issue.

**Comment by joshiste** [comment] 2016-08-08 15:28
The bug was caused by using an old nodejs version on the build server, which caused a webpack plugin to fail but unfortunatly this didn't break the build...

Fixed with a204453db96495ba94a488bff2881fe2b5e044b8. A fixed version will be published soon.

**Closed by joshiste** 2016-08-08 15:28 UTC
Labels: bug
