### ISSUE TITLE
TURBINE UI QS

### ISSUE THREAD

**Issue by bensonHe** [codecentric/spring-boot-admin#690] opened 2018-03-30 06:42 UTC
I when i use SPA  turbine ui  to show . the host is 64/s(is wrong),  but use the hystrix-dashboard is 200/s (is right). 
the turbine server url is the same.  SBA-SERVER/api/turbine/stream?cluster=api-gateway.

**Comment by bensonHe** [comment] 2018-03-30 06:44
the SPA version is 1.5.7 (ui-turbine, ui-hystrix)

**Comment by joshiste** [comment] 2018-03-30 09:49
Sorry but I don't understand what's the issue here can you describe you problem in detail and provide a sample project to reproduce the issue?

**Comment by tjuchniewicz** [comment] 2018-03-30 12:15
This is Hystrix Dashboard bug. See: https://github.com/Netflix/Hystrix/issues/1697

**Comment by joshiste** [comment] 2018-03-30 13:51
@tjuchniewicz thanks fo the info. I'm closing this issue since we can't solve that here.

**Closed by joshiste** 2018-03-30 13:51 UTC
Labels: waiting-for-feedback
