### ISSUE TITLE
Netty: Requests are failing after some time

### ISSUE THREAD

**Issue by deyanTG** [codecentric/spring-boot-admin#764] opened 2018-05-31 14:02 UTC
Hi, 
We are using SBA 2.0.0 and our application is written on Spring Boot 2.0.0. We are able to run the SBA instance but occasionally we are getting the following errors. 

**Firefox**
![mozila](https://user-images.githubusercontent.com/1578979/40786628-27b6f7aa-64f4-11e8-80d7-bdb8cff5b67d.png)

**Chrome**
![chrome](https://user-images.githubusercontent.com/1578979/40786667-41ae9708-64f4-11e8-90fa-3f990b9eef8a.png)

After 'refresh' it works fine for some time but eventually breaks out again.

**Comment by deyanTG** [comment] 2018-06-11 10:42
It depends... Sometimes the errors show up after a couple of seconds, sometimes several minutes are needed. I'd say it is not determinated.

This is another excerpt with open chrome console. 
![1](https://user-images.githubusercontent.com/1578979/41227097-5ad9e102-6d7c-11e8-856d-b5854447d9cf.png)

I'll provide and code repo as well, but I'am using simple SBA project with only one main method annotated with  `@EnableAdminServer`. 

There are only two configurations in application.properties of SBA.

`server.port=19000
management.security.enabled=false`

Client configurations related to SBA are the following:

`spring.boot.admin.client.url=http://127.0.0.1:19000
spring.boot.admin.client.instance.management-base-url=http://127.0.0.1:18080
management.endpoints.web.exposure.include=*`

**Comment by joshiste** [comment] 2018-06-11 11:02
What Java version and platform is it running on?

**Comment by deyanTG** [comment] 2018-06-11 11:07
java version "1.8.0_151"

Linux OS-0060 3.16.0-4-amd64 #1 SMP Debian 3.16.51-3 (2017-12-13) x86_64 GNU/Linux

**Comment by anandreddyakidi** [comment] 2018-06-11 22:40
Hi,

I am migrating spring boot admin client application from 1.5.7 to 2.0.0. I am getting below exception. How to resolve below exception.  Pease find my pom.xml also

`11 Jun 2018 16:24:44,820 INFO  AnnotationConfigApplicationContext:993 - Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@bcec361: startup date [Mon Jun 11 16:24:44 MDT 2018]; root of context hierarchy
11 Jun 2018 16:24:44,822 ERROR SpringApplication:833 - Application run failed
java.lang.NoSuchMethodError: org.springframework.core.annotation.AnnotationUtils.clearCache()V
	at org.springframework.context.support.AbstractApplicationContext.resetCommonCaches(AbstractApplicationContext.java:915)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:575)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:752)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:388)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:137)
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.bootstrapServiceContext(BootstrapApplicationListener.java:197)
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:104)
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:70)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:74)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:351)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:317)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1246)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1234)
	at com.movenetworks.DenormalizerTopologyApplication.main(DenormalizerTopologyApplication.java:115)`


`<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>myapplication</groupId>
    <artifactId>myapplication</artifactId>
    <version>10.2</version>

    <repositories>

        <repository>
            <id>confluent</id>
            <url>http://packages.confluent.io/maven/</url>
        </repository>

    </repositories>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.0.0.RELEASE</version>
        <relativePath/> 
    </parent>

    <properties>
        
        <start-class>com.movenetworks.DenormalizerTopologyApplication</start-class>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <clover.version>4.2.0</clover.version>
        <spring.kafka.version>2.1.6.RELEASE</spring.kafka.version>
    </properties>

	<dependencyManagement>
	    <dependencies>
	        <dependency>
	            <groupId>org.springframework.cloud</groupId>
	            <artifactId>spring-cloud-config</artifactId>
	            <version>2.0.0.RC2</version>
	            <type>pom</type>
	            <scope>import</scope>
	        </dependency>
	    </dependencies>
	</dependencyManagement>

    <dependencies>


    

    

<dependency>
    <groupId>org.apache.avro</groupId>
    <artifactId>avro</artifactId>
    <version>1.8.2</version>
</dependency>
    <dependency>
    <groupId>io.confluent</groupId>
    <artifactId>kafka-avro-serializer</artifactId>
    <version>4.0.0</version>
</dependency>

    	<dependency>
   			 <groupId>com.newrelic.agent.java</groupId>
   			 <artifactId>newrelic-java</artifactId>
  			 <version>3.42.0</version>
    		 <scope>provided</scope>
    		 <type>zip</type>
	</dependency>
	
	<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-security</artifactId>
</dependency>
		<dependency>
        	<groupId>org.springframework.cloud</groupId>
        	<artifactId>spring-cloud-starter-config</artifactId>
    	</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>

        <dependency>
            <groupId>io.confluent</groupId>
            <artifactId>monitoring-interceptors</artifactId>
            <version>4.0.0</version>
        </dependency>

        <dependency>
  			<groupId>org.slf4j</groupId>
  			<artifactId>slf4j-log4j12</artifactId>
  			<version>1.7.25</version>
		</dependency>

       

        <dependency>
            <groupId>org.apache.kafka</groupId>
            <artifactId>kafka-streams</artifactId>
            <version>1.0.0-cp1</version>
        </dependency>
        <dependency>
            <groupId>org.apache.kafka</groupId>
            <artifactId>kafka-streams</artifactId>
            <version>1.0.0-cp1</version>
            <classifier>test</classifier>
        </dependency>


        <dependency>
            <groupId>org.apache.kafka</groupId>
            <artifactId>kafka_2.11</artifactId>
            <version>1.0.0-cp1</version>
            <classifier>test</classifier>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-log4j12</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>log4j</groupId>
                    <artifactId>log4j</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        


        <dependency>
            <groupId>io.confluent</groupId>
            <artifactId>kafka-schema-registry</artifactId>
            <version>4.0.0</version>
            
            <classifier>tests</classifier>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-log4j12</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>log4j</groupId>
                    <artifactId>log4j</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>io.confluent</groupId>
            <artifactId>kafka-schema-registry</artifactId>
            <version>4.0.0</version>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-log4j12</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>log4j</groupId>
                    <artifactId>log4j</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.apache.kafka</groupId>
            <artifactId>kafka-clients</artifactId>
            <version>1.0.0-cp1</version>

        </dependency>


        <dependency>
            <groupId>org.apache.kafka</groupId>
            <artifactId>kafka-clients</artifactId>
            <version>1.0.0-cp1</version>
            <classifier>test</classifier>
            <exclusions>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-log4j12</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>log4j</groupId>
                    <artifactId>log4j</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            
            <groupId>com.101tec</groupId>
            <artifactId>zkclient</artifactId>
            <version>0.9</version>
            <exclusions>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-log4j12</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>log4j</groupId>
                    <artifactId>log4j</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.json</groupId>
            <artifactId>json</artifactId>
            <version>20150729</version>
        </dependency>


      

        <dependency>
            <groupId>org.apache.avro</groupId>
            <artifactId>avro</artifactId>
            <version>1.8.0</version>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <version>3.3.0</version>
            <scope>test</scope>
        </dependency>
        


        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
            <exclusions>
            	<exclusion>
            		<groupId>org.slf4j</groupId>
            		<artifactId>log4j-over-slf4j</artifactId>
            	</exclusion>
            	<exclusion>
            		<groupId>ch.qos.logback</groupId>
            		<artifactId>logback-classic</artifactId>
            	</exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>de.codecentric</groupId>
            <artifactId>spring-boot-admin-starter-client</artifactId>
            <version>2.0.0</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.kafka</groupId>
            <artifactId>spring-kafka</artifactId>
            <version>${spring.kafka.version}</version>
        </dependency>


        <dependency>
            <groupId>de.codecentric</groupId>
            <artifactId>spring-boot-admin-server</artifactId>
            <version>2.0.0</version>
        </dependency>
        <dependency>
            <groupId>de.codecentric</groupId>
            <artifactId>spring-boot-admin-server-ui</artifactId>
            <version>2.0.0</version>
        </dependency>

        
        <dependency>
            <groupId>org.apache.curator</groupId>
            <artifactId>curator-test</artifactId>
            <version>2.0.0-incubating</version>
        </dependency>

        <dependency>
            <groupId>com.newrelic.agent.java</groupId>
            <artifactId>newrelic-api</artifactId>
            <version>3.42.0</version>
        </dependency>
        <dependency>
            <groupId>org.powermock</groupId>
            <artifactId>powermock-api-mockito</artifactId>
            <version>1.6.5</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.powermock</groupId>
            <artifactId>powermock-module-junit4</artifactId>
            <version>1.6.5</version>
            <scope>test</scope>
        </dependency>


    </dependencies>
    <build>

        <sourceDirectory>src/main/java</sourceDirectory>
        <plugins>

            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>2.0.0.RELEASE</version>


                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-dependency-plugin</artifactId>
    <version>3.1.1</version>
    <executions>
        <execution>
            <phase>prepare-package</phase>
            <goals>
                <goal>unpack-dependencies</goal>
            </goals>
            <configuration>
                <includeArtifactIds>newrelic-java</includeArtifactIds>
                <excludes>newrelic.yml</excludes>
                <outputDirectory>${project.build.outputDirectory}</outputDirectory>
            </configuration>
        </execution>
    </executions>
</plugin>

<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-jar-plugin</artifactId>
    <configuration>
        <archive>
            <manifestEntries>
                <Premain-Class>com.newrelic.bootstrap.BootstrapAgent</Premain-Class>
                <Can-Redefine-Classes>true</Can-Redefine-Classes>
                <Can-Retransform-Classes>true</Can-Retransform-Classes>
            </manifestEntries>
        </archive>
    </configuration>
</plugin>
<plugin>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-maven-plugin</artifactId>
    <configuration>
        <mainClass>com.mycompany.MyApplication</mainClass>
    </configuration>
</plugin>

            <plugin>
                <groupId>io.confluent</groupId>
                <artifactId>kafka-schema-registry-maven-plugin</artifactId>
                <version>4.0.0</version>
                <configuration>
                    <schemaRegistryUrls>
                        <param>http://myhost:8081</param>
                    </schemaRegistryUrls>
                    <subjects>
                        <TestSubject000-key>src/main/avro/TestSubject000-Key.avsc</TestSubject000-key>
                        <TestSubject000-value>src/main/avro/TestSubject000-Value.avsc</TestSubject000-value>
                    </subjects>
                </configuration>
                <goals>
                    <goal>test-compatibility</goal>
                </goals>
            </plugin>
            <plugin>
                <groupId>org.openclover</groupId>
                <artifactId>clover-maven-plugin</artifactId>
                <version>${clover.version}</version>
                <configuration>
                    <generateHtml>true</generateHtml>
                    <jdk>1.8</jdk>
                </configuration>
                <executions>
                    <execution>
                        <phase>verify</phase>
                        <goals>
                            <goal>instrument</goal>
                            <goal>check</goal>
                            <goal>log</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>


        </plugins>
    </build>
    <reporting>
        <plugins>
            <plugin>
                <groupId>org.openclover</groupId>
                <artifactId>clover-maven-plugin</artifactId>
                
                
                
            </plugin>
        </plugins>
    </reporting>
</project>
`

**Comment by joshiste** [comment] 2018-06-12 13:56
is the admin server running on tomcat (did you include `spring-boot-starter-web`?) or is it running on netty?

**Comment by deyanTG** [comment] 2018-06-12 14:09
These are declared dependencies:

```
<dependency>
<groupId>de.codecentric</groupId>
 <artifactId>spring-boot-admin-starter-server</artifactId>
 <version>2.0.0</version>
</dependency>

<dependency>
 <groupId>org.springframework.boot</groupId>
 <artifactId>spring-boot-starter</artifactId>
</dependency>

```

These are  dependenciess from client side

```
<dependency>
 <groupId>org.springframework.boot</groupId>
 <artifactId>spring-boot-starter-actuator</artifactId>
</dependency>

<dependency>
 <groupId>de.codecentric</groupId>
 <artifactId>spring-boot-admin-starter-client</artifactId>
 <version>2.0.0</version>
</dependency>
```

As I said,we're using Spring Boot 2.0.0

`2018-06-12 16:59:08.833  INFO 10257 --- [ctor-http-nio-1] r.ipc.netty.tcp.BlockingNettyContext     : Started HttpServer on /0:0:0:0:0:0:0:0:19000
2018-06-12 16:59:08.834  INFO 10257 --- [           main] o.s.b.web.embedded.netty.NettyWebServer  : Netty started on port(s): 19000`

Netty container is in use

**Comment by joshiste** [comment] 2018-06-12 14:15
Please add the `spring-boot-starter-web` and try running on tomcat

**Comment by deyanTG** [comment] 2018-06-12 15:00
After switching to tomcat (as  [joshiste](https://github.com/joshiste) suggested) we don't get the above mentioned problems. Will monitor the system for some time but until now it never worked for so much time without getting rendering problems.

**Comment by joshiste** [comment] 2018-06-25 20:29
I could not reproduce this issue on netty with spring boot 2.0.3.RELEASE.
As there is a suitable workaround (using tomcat) I'm closing this issue. 
In case you really want to use netty (for whatever reason) please provide something to reproduce this problem.

**Closed by joshiste** 2018-06-25 20:29 UTC
Labels: bug, server
