### ISSUE TITLE
spring boot (2.5.3) and spring admin starter server incompability (2.5.3) version

### ISSUE THREAD

**Issue by sehmusaydogdu** [codecentric/spring-boot-admin#2017] opened 2022-04-11 14:54 UTC
I'm getting an error when trying to use admin-server. Below you can find the POM file information

     <parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.5.3</version>
     </parent>

     <dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
		<dependency>
			<groupId>de.codecentric</groupId>
			<artifactId>spring-boot-admin-starter-server</artifactId>
		</dependency>
		<dependency>
			<groupId>io.pivotal.spring.cloud</groupId>
			<artifactId>spring-cloud-services-starter-service-registry</artifactId>
		</dependency>
	</dependencies>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>2020.0.3</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
			<dependency>
				<groupId>io.pivotal.spring.cloud</groupId>
				<artifactId>spring-cloud-services-dependencies</artifactId>
				<version>3.3.0</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
			<dependency>
				<groupId>de.codecentric</groupId>
				<artifactId>spring-boot-admin-dependencies</artifactId>
				<version>2.5.0</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

Below you can find the error log information.

**2022-04-11T17:44:15.08+0300 [APP/PROC/WEB/0] OUT ***************************
2022-04-11T17:44:15.08+0300 [APP/PROC/WEB/0] OUT APPLICATION FAILED TO START
2022-04-11T17:44:15.08+0300 [APP/PROC/WEB/0] OUT ***************************
2022-04-11T17:44:15.08+0300 [APP/PROC/WEB/0] OUT Description:
2022-04-11T17:44:15.08+0300 [APP/PROC/WEB/0] OUT The bean 'eurekaInstanceConfigBean', defined in class path resource [io/pivotal/spring/cloud/service/registry/EurekaInstanceAutoConfiguration.class], could not be registered. A bean with that name has already been defined in class path resource [org/springframework/cloud/netflix/eureka/EurekaClientAutoConfiguration.class] and overriding is disabled.
2022-04-11T17:44:15.08+0300 [APP/PROC/WEB/0] OUT Action:
2022-04-11T17:44:15.08+0300 [APP/PROC/WEB/0] OUT Consider renaming one of the beans or enabling overriding by setting spring.main.allow-bean-definition-overriding=true**

Then I added java options spring.main.allow-bean-definition-overriding=true. Error log changed.

**2022-04-11T17:33:06.45+0300 [APP/PROC/WEB/0] OUT 2022-04-11 17:33:06.454  INFO 14 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2022-04-11T17:33:06.47+0300 [APP/PROC/WEB/0] OUT 2022-04-11 17:33:06.479  INFO 14 --- [           main] ConditionEvaluationReportLoggingListener :
2022-04-11T17:33:06.47+0300 [APP/PROC/WEB/0] OUT Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-04-11T17:33:06.49+0300 [APP/PROC/WEB/0] OUT 2022-04-11 17:33:06.496 ERROR 14 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   :
2022-04-11T17:33:06.49+0300 [APP/PROC/WEB/0] OUT ***************************
2022-04-11T17:33:06.49+0300 [APP/PROC/WEB/0] OUT APPLICATION FAILED TO START
2022-04-11T17:33:06.49+0300 [APP/PROC/WEB/0] OUT ***************************
2022-04-11T17:33:06.49+0300 [APP/PROC/WEB/0] OUT Description:
2022-04-11T17:33:06.49+0300 [APP/PROC/WEB/0] OUT Field optionalArgs in org.springframework.cloud.netflix.eureka.EurekaClientAutoConfiguration$RefreshableEurekaClientConfiguration required a single bean, but 2 were found:
2022-04-11T17:33:06.49+0300 [APP/PROC/WEB/0] OUT     - restTemplateDiscoveryClientOptionalArgs: defined by method 'restTemplateDiscoveryClientOptionalArgs' in class path resource [org/springframework/cloud/netflix/eureka/config/DiscoveryClientOptionalArgsConfiguration.class]
2022-04-11T17:33:06.49+0300 [APP/PROC/WEB/0] OUT     - discoveryClientOptionalArgs: defined by method 'discoveryClientOptionalArgs' in class path resource [io/pivotal/spring/cloud/service/registry/EurekaClientOAuth2AutoConfiguration.class]
2022-04-11T17:33:06.49+0300 [APP/PROC/WEB/0] OUT Action:
2022-04-11T17:33:06.49+0300 [APP/PROC/WEB/0] OUT Consider marking one of the beans as @Primary, updating the consumer to accept multiple beans, or using @Qualifier to identify the bean that should be consumed**

**Comment by SteKoe** [comment] 2022-04-12 07:26
Hi @sehmusaydogdu,

I have set up an empty Spring project using your POM and was not able to reproduce your issue. It seems to be related to your Eureka configuration but not SBA itself:
 
> The bean 'eurekaInstanceConfigBean', defined in class path resource [io/pivotal/spring/cloud/service/registry/EurekaInstanceAutoConfiguration.class], could not be registered. A bean with that name has already been defined in class path resource [org/springframework/cloud/netflix/eureka/EurekaClientAutoConfiguration.class] and overriding is disabled.

Please recheck your Eureka configuration. If you think that everything is fine, provide a demo project which reproduces this issue. Thank you :)

**Comment by kvmw** [comment] 2022-04-19 15:34
I ran to the same problem in cloud-foundry.  seems like spring-boot-admin is defining another `RestTemplateDiscoveryClientOptionalArgs`  which causing the bean duplication issue.

**Comment by ulischulte** [comment] 2022-04-22 12:39
Hi @sehmusaydogdu ,
since there seems to be a workaround for this problem and the issue is already addressed in https://github.com/pivotal-cf/spring-cloud-services-starters/issues/278 , I will close this issue.

**Closed** 2022-04-22 12:39 UTC
Labels: bug, discussion
