### ISSUE TITLE
download logfile is 404

### ISSUE THREAD

**Issue by qwwfxl** [codecentric/spring-boot-admin#947] opened 2018-09-26 10:42 UTC
![default](https://user-images.githubusercontent.com/17565026/46074795-2b0b3500-c1bb-11e8-8f35-25beb8dd9cea.png)
![default](https://user-images.githubusercontent.com/17565026/46074840-4aa25d80-c1bb-11e8-9132-4709b9060191.png)

the client service configuration is:
![default](https://user-images.githubusercontent.com/17565026/46074910-81787380-c1bb-11e8-8d62-d9ec371f31a9.png)

can help me?

**Comment by joshiste** [comment] 2018-09-26 15:09
duplicate of #846

**Closed by joshiste** 2018-09-26 15:09 UTC
