### ISSUE TITLE
spring boot admin registers with CF UUID

### ISSUE THREAD

**Issue by phopper-pivotal** [codecentric/spring-boot-admin#362] opened 2016-12-19 21:19 UTC
using version 1.4.4 in server and clients. when pushing a client to Cloud Foundry (not using Eureka) the client is registering with spring boot admin using the UUID of the application.

client-a

Starting ClientAApplication on d455a24f-870e-4734-5423-f9bbc4aa5fd1 with PID 19 (/home/vcap/app/BOOT-INF/classes started by vcap in /home/vcap/app)

Application registered itself as {managementUrl=http://d455a24f-870e-4734-5423-f9bbc4aa5fd1:8080, healthUrl=http://d455a24f-870e-4734-5423-f9bbc4aa5fd1:8080/health, serviceUrl=http://d455a24f-870e-4734-5423-f9bbc4aa5fd1:8080, name=client-a, id=5f8e3200, statusInfo={status=UNKNOWN, timestamp=1482181921832}}

I've looked to setting health-url and management-url via application.yml but aren't used. Any suggestions?

[application.yml]
```yaml
spring:
  application:
    name: client-a
  boot:
    admin:
      url: https://spring-admin-server.cfapps.io
      client:
         health-url: https://client-a.cfapps.io/health
         management-url: https://client-a.cfapps.io
```

**Comment by joshiste** [comment] 2016-12-19 21:42
Did you check your `/env` endpoint that the values are really set?

**Comment by phopper-pivotal** [comment] 2016-12-19 21:50
did not validate until now but here is /env


"applicationConfig: [classpath:/application.yml]": {
"spring.application.name": "client-a",
"spring.boot.admin.url": "https://spring-admin-server.cfapps.io",
"spring.boot.admin.client.enabled": true,
"spring.boot.admin.client.health-url": "https://client-a.cfapps.io/health",
"spring.boot.admin.client.management-url": "https://client-a.cfapps.io"
},

**Comment by joshiste** [comment] 2016-12-19 21:54
I tried using your `application.yml` and the spring-boot-admin-sample-1.4.4.jar from http://repo1.maven.org. The application registers correctly. 

Can you reproduce the error outside of CF? If yes can you provide me a sample project to reproduce the problem?

**Comment by joshiste** [comment] 2016-12-19 21:55
Also you could check the `/configprops` endpoint to see which values get actually bound.

**Comment by phopper-pivotal** [comment] 2016-12-19 21:58
uses localhost:port for client-a when running standalone on macbook.

here's /configprops output, should the serverUrl be set as well?


"
spring.boot.admin.client-de.codecentric.boot.admin.config.AdminClientProperties
": {"prefix": "spring.boot.admin.client","properties": {"serviceUrl": "
http://fb163fd5-3f8b-49b9-73b6-f892a88849ef:8080","name": "client-a","
managementUrl": "https://client-a.cfapps.io","healthUrl": "
https://client-a.cfapps.io/health","preferIp": false}},

**Comment by phopper-pivotal** [comment] 2016-12-19 22:07
so added spring.boot.admin.client.service-url to my application.yml and it picked up the correct URL for the service endpoint in spring boot admin. its now reporting the application as UP and can click on "details"

note; before it was registering but with https://<the cf uuid> instead of the actual route (or service-url).

**Comment by joshiste** [comment] 2016-12-19 22:22
The service-url is just informational.
So when I get it right you solved the issue yourself? Can we close the issue?

**Comment by phopper-pivotal** [comment] 2016-12-19 22:30
well if service-url is only informational then this may still be an issue. let me get this repo put together and made public.

**Comment by phopper-pivotal** [comment] 2016-12-19 23:23
added this GitHub repo that has four separate services, all of which were pushed to Pivotal Web Services. to push to PWS, you may want to update the manifest to add a random host (or route).

https://github.com/phopper-pivotal/spring-admin-services

**Comment by joshiste** [comment] 2016-12-20 05:27
When I checkout your project, remove the service-url from the `client-a/src/main/resources/application.yml` and run it using `spring-boot:run` the application registers itself as intended:
```log
2016-12-20 06:24:02.582  INFO 24293 --- [gistrationTask1] d.c.b.a.services.ApplicationRegistrator  : Application registered itself as {managementUrl=https://client-a.cfapps.io, healthUrl=https://client-a.cfapps.io/health, serviceUrl=http://johannes-XPS:8080, name=client-a, id=38aee2c5, statusInfo={status=UP, timestamp=1482211429432}}
```

I don't see any problem here that needs to be fixed...?

**Comment by phopper-pivotal** [comment] 2016-12-20 14:54
Its when running it under Cloud Foundry that the app GUID is used instead
of the service-url. If that isn't a concern then I can close. Just curious
why it's picking up the app GUID instead of the actual route URL.

**Comment by joshiste** [comment] 2016-12-20 21:38
Ok now I tried to deploy your project using PCF Dev on my local machine.

Your projects contain an 'application.yml` and an empty `application.properties` I delete the latter one.

When I use following `application.yml` for the client-a, everything works as expected - I can hardly find any problem which needs to be fixed. 

```yml
spring:
  application:
    name: client-a
  boot:
    admin:
      url: http://spring-admin-server.local.pcfdev.io
      client:
         health-url: http://${vcap.application.uris[0]}/health
         management-url: http://${vcap.application.uris[0]}
```

Is it possible that on your first try the `application.yml` just was incorrect?

**Comment by phopper-pivotal** [comment] 2016-12-20 22:20
deleted application.properties and pushed updated app to CF. still using GUID as the url for serviceUrl. we can close ticket as app is being deployed to Tomcat and service-url required in application.yml. you can close this issue.

**Comment by joshiste** [comment] 2016-12-20 22:26
?The sample you provided was a boot application...?

> ...still using GUID as the url for serviceUr ... app is being deployed to Tomcat and service-url required in application.yml

Hmm I don't get it. When you doing a war deployment the url isn't computed by SBA client... and you need to specify it so, where should the GUID come from?

**Comment by phopper-pivotal** [comment] 2016-12-20 22:29
Yeah that's exactly what I was wondering. It only appears as instance_id in
actuators /envs for that application, even then only under vcap variables.
Yup, all four in that repository are Spring Boot applications. Intriguing
indeed.

**Comment by joshiste** [comment] 2016-12-20 22:33
So should I be able to reproduce the problem using PCF Dev and your github repository?

**Comment by phopper-pivotal** [comment] 2016-12-20 22:35
have you a pivotal web services account? if not, let me prove out on
PCFDev, have only been using on-premise PCF and PWS.

**Comment by joshiste** [comment] 2016-12-20 22:37
> have you a pivotal web services account?
No unfortunately not.

**Comment by phopper-pivotal** [comment] 2016-12-20 22:57
let me prove out on PCFDev then.

**Comment by phopper-pivotal** [comment] 2016-12-20 23:17
pushed the spring boot admin server and client-c. client-c did not set the service-url in application.yml (and no application.properties). while the app that is bound to the admin server is not using the GUID it also does not use the route or application name. see attached screen shots. I could not find where its pulling that unique name from (checked /env and /configprops). weird.

![screen shot 2016-12-20 at 4 13 20 pm](https://cloud.githubusercontent.com/assets/13732543/21371666/d32a824c-c6cf-11e6-8cd1-df1115193284.png)

![screen shot 2016-12-20 at 4 14 32 pm](https://cloud.githubusercontent.com/assets/13732543/21371673/db19aef6-c6cf-11e6-8017-f499e8331002.png)

**Comment by joshiste** [comment] 2016-12-21 07:43
When the service-/health-/managment-url are not configured explicit, they're "guessed" for fat-jar boot applications based on `InetAdress.getLocalHost()` / `server.adress` /  `server.port` / `server.context-path`.
This is described in the [Docs](http://codecentric.github.io/spring-boot-admin/1.4.4/#spring-boot-admin-client) and is done by the [ApplicationFactory](https://github.com/codecentric/spring-boot-admin/blob/master/spring-boot-admin-starter-client/src/main/java/de/codecentric/boot/admin/client/registration/DefaultApplicationFactory.java#L55).

And also it's intended behaviour.

At first I thought that you said the health- and management-url are guessed even though you specified them explicitly. If this is not the case then everything works as expected.

**Comment by phopper-pivotal** [comment] 2016-12-21 13:47
that's fair. your original statement that service-url is informational
threw me. you can close this ticket.

**Closed** 2016-12-21 13:52 UTC
Labels: waiting-for-feedback
