### ISSUE TITLE
issues running boot admin

### ISSUE THREAD

**Issue by harestupramadharma** [codecentric/spring-boot-admin#183] opened 2016-04-18 12:32 UTC
I have the same problem with tobiasflohre #165. and I've tried the solution given by @joshiste in fb94c57
After add the head request for the logfile, I build it and deploy it in my artifactory. 

But, when I try to access the spring boot admin url, I got nothing.
and this is the log error

```
2016-04-18 19:33:26,989 INFO  [org.springframework.boot.actuate.endpoint.jmx.EndpointMBeanExporter] (MSC service thread 1-4) Located managed bean 'traceEndpoint': registering with JMX server as MBean [org.springframework.boot:type=Endpoint,name=traceEndpoint]
2016-04-18 19:33:26,992 ERROR [org.springframework.boot.actuate.endpoint.jmx.EndpointMBeanExporter] (MSC service thread 1-4) Could not register MBean for endpoint [traceEndpoint]: org.springframework.jmx.export.UnableToRegisterMBeanException: Unable to register MBean [org.springframework.boot.actuate.endpoint.jmx.DataEndpointMBean@5e707dc9] with key 'traceEndpoint'; nested exception is javax.management.InstanceAlreadyExistsException: org.springframework.boot:type=Endpoint,name=traceEndpoint
	at org.springframework.jmx.export.MBeanExporter.registerBeanNameOrInstance(MBeanExporter.java:625) [spring-context-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.boot.actuate.endpoint.jmx.EndpointMBeanExporter.registerEndpoint(EndpointMBeanExporter.java:183) [spring-boot-actuator-1.3.3.RELEASE.jar:1.3.3.RELEASE]
	at org.springframework.boot.actuate.endpoint.jmx.EndpointMBeanExporter.locateAndRegisterEndpoints(EndpointMBeanExporter.java:163) [spring-boot-actuator-1.3.3.RELEASE.jar:1.3.3.RELEASE]
	at org.springframework.boot.actuate.endpoint.jmx.EndpointMBeanExporter.doStart(EndpointMBeanExporter.java:154) [spring-boot-actuator-1.3.3.RELEASE.jar:1.3.3.RELEASE]
	at org.springframework.boot.actuate.endpoint.jmx.EndpointMBeanExporter.start(EndpointMBeanExporter.java:277) [spring-boot-actuator-1.3.3.RELEASE.jar:1.3.3.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:173) [spring-context-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:51) [spring-context-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:346) [spring-context-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:149) [spring-context-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:112) [spring-context-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:852) [spring-context-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:140) [spring-boot-1.3.3.RELEASE.jar:1.3.3.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541) [spring-context-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118) [spring-boot-1.3.3.RELEASE.jar:1.3.3.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:766) [spring-boot-1.3.3.RELEASE.jar:1.3.3.RELEASE]
	at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:361) [spring-boot-1.3.3.RELEASE.jar:1.3.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307) [spring-boot-1.3.3.RELEASE.jar:1.3.3.RELEASE]
	at org.springframework.boot.context.web.SpringBootServletInitializer.run(SpringBootServletInitializer.java:149) [spring-boot-1.3.3.RELEASE.jar:1.3.3.RELEASE]
	at org.springframework.boot.context.web.SpringBootServletInitializer.createRootApplicationContext(SpringBootServletInitializer.java:129) [spring-boot-1.3.3.RELEASE.jar:1.3.3.RELEASE]
	at org.springframework.boot.context.web.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.java:85) [spring-boot-1.3.3.RELEASE.jar:1.3.3.RELEASE]
	at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:175) [spring-web-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:183) [undertow-servlet-1.1.8.Final.jar:1.1.8.Final]
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:87)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService.start(UndertowDeploymentService.java:72)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110) [rt.jar:1.7.0_11]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603) [rt.jar:1.7.0_11]
	at java.lang.Thread.run(Thread.java:722) [rt.jar:1.7.0_11]
Caused by: javax.management.InstanceAlreadyExistsException: org.springframework.boot:type=Endpoint,name=traceEndpoint
	at com.sun.jmx.mbeanserver.Repository.addMBean(Repository.java:437) [rt.jar:1.7.0_11]
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerWithRepository(DefaultMBeanServerInterceptor.java:1898) [rt.jar:1.7.0_11]
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerDynamicMBean(DefaultMBeanServerInterceptor.java:966) [rt.jar:1.7.0_11]
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(DefaultMBeanServerInterceptor.java:900) [rt.jar:1.7.0_11]
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:324) [rt.jar:1.7.0_11]
	at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:512) [rt.jar:1.7.0_11]
	at org.jboss.as.jmx.PluggableMBeanServerImpl$TcclMBeanServer.registerMBean(PluggableMBeanServerImpl.java:1493)
	at org.jboss.as.jmx.PluggableMBeanServerImpl.registerMBean(PluggableMBeanServerImpl.java:896)
	at org.springframework.jmx.support.MBeanRegistrationSupport.doRegister(MBeanRegistrationSupport.java:195) [spring-context-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.jmx.export.MBeanExporter.registerBeanInstance(MBeanExporter.java:678) [spring-context-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.jmx.export.MBeanExporter.registerBeanNameOrInstance(MBeanExporter.java:621) [spring-context-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	... 28 more
```
and this

```
2016-04-18 18:58:41,343 ERROR [org.springframework.boot.context.web.ErrorPageFilter] (default task-3) Cannot forward to error page for request [/index.html] as the response has already been committed. As a result, the response may have the wrong status code. If your application is running on WebSphere Application Server you may be able to resolve this problem by setting com.ibm.ws.webcontainer.invokeFlushAfterService to false
```

What should I do then?

**Comment by joshiste** [comment] 2016-04-18 13:10
Your errors looks unrelated to spring boot admin me.
What really confuses me is `com.ibm.ws.webcontainer.invokeFlushAfterService` in the error message and the `org.wildfly.extension.undertow.deployment.UndertowDeploymentService` int the stacktrace. The former is a hint for a webshpere deployment and the latter for a undertow/Jboss deployment.
Is it possible you messed up your application-config somehow? 
Do you have a small sample to reproduce the error? What platform are you running on?

Btw you don't need to make snapshot-builds yourself. You can grab 'em here:
```xml
<snapshotRepository>
 <id>sonatype-nexus-snapshots</id>
 <name>Sonatype Nexus Snapshots</name>
 <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
</snapshotRepository>
```

**Comment by joshiste** [comment] 2016-04-18 13:18
Regarding the duplicate MBeans you might need to configure a custom domain, in case there are multiple boot applications running in the same VM. Have a look at http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready-custom-mbean-names

**Comment by harestupramadharma** [comment] 2016-04-18 13:28
well, that true @joshiste . Ihave some boot application in the same VM. I'll fix it. :)

But I still don't understand, cause if i change the dependencies version of spring boot admin server ui in 1.3.2 release, it's have no error (except the logfile button). but when I use the 1.3.3-snapshot builds by my self, i got that error. 

oh, stupid me. so, I dont need to make snapshot-build by my self? then how to use that <snapshotRepository> tag? should I add it into my pom?

**Comment by joshiste** [comment] 2016-04-18 13:32
> then how to use that tag? should I add it into my pom? 

Add the following lines to you pom.xml an reference the `1.3.3-SNAPSHOT` version

```xml
<repositories>
        <repository>
             <id>sonatype-nexus-snapshots</id>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
        </repository>
</repositories>
```

**Comment by joshiste** [comment] 2016-04-18 17:16
> I have the same problem with tobiasflohre #165

I really doubt that, cause it looks like you are deploying to a servlet/ee container. And when you doing that [you can't set a different port for the management endpoints](https://github.com/spring-projects/spring-boot/issues/552).
And maybe that explains the weird undertow/websphere messages - since boot maybe tries to spin up a servlet container while itself runs in one...

**Comment by joshiste** [comment] 2016-04-18 17:18
I'm closing this issue right now, since your problems are not spring boot admin related.

**Closed by joshiste** 2016-04-18 17:18 UTC
Labels: help wanted, waiting-for-feedback

**Comment by harestupramadharma** [comment] 2016-04-19 01:05
okay, thankyou @joshiste , I'll fix the rest. really appreciate your help and your fast responses.
