### ISSUE TITLE
Slack Integration - 400 Bad Request

### ISSUE THREAD

**Issue by mrmarbles** [codecentric/spring-boot-admin#445] opened 2017-05-05 18:21 UTC
I've implemented simple boot admin application that is also a Eureka (via Spring Cloud) discovery client and so far everything works as expected.  However when I attempted to integrate slack notifications I'm seeing the following exception in the application logs - of course no slack notifications are being received either.  I've tested the webhooks URL outside of the spring admin app and all works as expected.

Here's my config;
```
spring:
  boot:
    admin:
      notify:
        slack:
          webhook-url: https://hooks.slack.com/****valid-url****
```

And here's the resulting exception when discovery client applications change status;
```
org.springframework.web.client.HttpClientErrorException: 400 Bad Request
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:700)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:653)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:628)
	at org.springframework.web.client.RestTemplate.postForEntity(RestTemplate.java:423)
	at de.codecentric.boot.admin.notify.SlackNotifier.doNotify(SlackNotifier.java:58)
	at de.codecentric.boot.admin.notify.AbstractEventNotifier.notify(AbstractEventNotifier.java:39)
	at de.codecentric.boot.admin.notify.NotifierListener.onClientApplicationEvent(NotifierListener.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:253)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:174)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:137)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:167)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:383)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:350)
	at de.codecentric.boot.admin.registry.StatusUpdater.updateStatus(StatusUpdater.java:78)
	at de.codecentric.boot.admin.registry.StatusUpdateApplicationListener$1.run(StatusUpdateApplicationListener.java:47)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

I'm using 1.5.0;
```
<dependency>
            <groupId>de.codecentric</groupId>
            <artifactId>spring-boot-admin-server</artifactId>
            <version>1.5.0</version>
        </dependency>

        <dependency>
            <groupId>de.codecentric</groupId>
            <artifactId>spring-boot-admin-server-ui</artifactId>
            <version>1.5.0</version>
        </dependency>

        <dependency>
            <groupId>de.codecentric</groupId>
            <artifactId>spring-boot-admin-server-ui-hystrix</artifactId>
            <version>1.5.0</version>
        </dependency>
```

**Comment by joshiste** [comment] 2017-05-05 21:46
can you please set the logger for `org.springframework.web.client.RestTemplate` to debug and post the log details (headers + body). Is your request sent via a proxy?

**Comment by joshiste** [comment] 2017-05-14 18:56
I'm closing this issue due to missing feedback. The current version works for me.
At best you provide a sample project to reproduce the error or at least some more information.

**Comment by w3blogfr** [comment] 2017-07-23 14:42
I set the logger org.springframework.web.client.RestTemplate to debug
Here was the result
`
2017-07-23 15:39:11.658 DEBUG 16765 --- [    updateTask1] o.s.web.client.RestTemplate              : Setting request Accept header to [application/xml, text/xml, application/json, application/*+xml, application/*+json]
2017-07-23 15:39:11.658 DEBUG 16765 --- [    updateTask1] o.s.web.client.RestTemplate              : Writing [{attachments=[{color=danger, mrkdwn_in=[text], text=*myApp* (eb746130) is *OFFLINE*}], username=Spring Boot Admin}] using [org.springframework.http.converter.xml.MappingJackson2XmlHttpMessageConverter@46e79427]
`

restTemplate send message in xml instead of json

I have a simply spring boot application with eureka server and Spring boot admin. MappingJackson2XmlHttpMessageConverter is before MappingJackson2HttpMessageConverter in the converter list


`
restTemplate.setMessageConverters(Arrays.asList(new MappingJackson2HttpMessageConverter()));
`

**Comment by joshiste** [comment] 2017-07-23 16:37
@w3blogfr thanks for investigating this issue. I'll have a look at your PR

**Closed** 2017-07-23 16:43 UTC
Labels: bug, server
