### ISSUE TITLE
Other Email Notifications

### ISSUE THREAD

**Issue by KarthikLearn** [codecentric/spring-boot-admin#1532] opened 2020-11-10 11:02 UTC
Currently SBA server sending Email notification for APP DOWN and UP option. Is there any option to send mail for the following categories Thread count threshold, CPU percent threshold, Memory threshold , Data source changes

**Comment by joshiste** [comment] 2020-11-10 11:56
duplicate of #1227

**Closed by joshiste** 2020-11-10 11:56 UTC
Labels: duplicate, enhancement
