### ISSUE TITLE
Integrate Hystrix Dashboard into the Spring Boot Admin Server

### ISSUE THREAD

**Issue by mrumpf** [codecentric/spring-boot-admin#241] opened 2016-08-01 15:28 UTC
The following page contains some info about how to integrate the Hystrix Dashboard view into existing applications:
https://github.com/Netflix/Hystrix/wiki/Dashboard#customizing-and-embedding

It would be great if Spring Boot Admin would automatically show a tab for Hystrix, when the endpoint /hystrix.stream is available for a Spring Boot application.
See https://github.com/VanRoy/spring-cloud-dashboard#circuit-breaker

**Comment by cforce** [comment] 2016-08-10 10:31
duplicate of https://github.com/codecentric/spring-boot-admin/issues/147 ?

**Comment by joshiste** [comment] 2016-08-10 10:46
you're right. Didn't spot it.
closing due to duplication of #147

**Closed by joshiste** 2016-08-10 10:46 UTC
Labels: duplicate
