### ISSUE TITLE
sba + concul   service can not be monitored

### ISSUE THREAD

**Issue by zhujiebing** [codecentric/spring-boot-admin#1224] opened 2019-07-25 05:21 UTC
I use spring cloud version is Greenwich.SR2,  spring boot version is 2.1.6.RELEASE,  sba version is 2.1.6.    consul  is  Service discovery。    I met a problem，Only services before the admin is started can be monitored。 And A warning appears :  

!!!
Streaming through a reactive type requires an Executor to write to the response.
Please, configure a TaskExecutor in the MVC config under "async support".
The SimpleAsyncTaskExecutor currently in use is not suitable under load.
-------------------------------
Controller:	de.codecentric.boot.admin.server.web.ApplicationsController
Method:		applicationsStream
Returning:	reactor.core.publisher.Flux<org.springframework.http.codec.ServerSentEvent<de.codecentric.boot.admin.server.web.ApplicationsController$Application>>
!!!

I hope to get your answer，  thank you very much。

**Comment by joshiste** [comment] 2019-07-25 15:42
Can you provide a project to reproduce the issue?

**Comment by joshiste** [comment] 2019-07-25 15:54
I can't reproduce the error using the `spring-boot-admin-sample-consul`

**Comment by zhujiebing** [comment] 2019-07-26 07:44
thanks!  I reference spring-boot-admin-sample-consul  and I have already solved this problem。
Now,I Full reference to spring-boot-admin-sample-consul.  And I have another problem，when I add spring-boot-starter-mail  jar,  and i add mail configuration  :
  profiles:
    active:
      - secure
  boot:
    admin:
      discovery:
        ignored-services: consul

## EMAIL REMIDER
spring.mail.host: smtp.qq.com
spring.mail.username: 408989025@qq.com
spring.mail.password: 123456
spring.boot.admin.notify.mail.to: 1483864326@qq.com
spring.boot.admin.notify.mail.from: 408989025@qq.com


Can only receive admin server‘s  Up and down email reminder，  can not receive other services's
Up and down email reminder.   And admin server throw an exception :  

Couldn't retrieve status for Instance(id=b6c58bcdf63e, version=3, registration=Registration(name=consul-example......

java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 10000ms in 'map' (and no fallback has been configured)
at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.handleTimeout(FluxTimeout.java:288) [reactor-core-3.3.0.M2.jar:3.3.0.M2]
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.doTimeout(FluxTimeout.java:273) [reactor-core-3.3.0.M2.jar:3.3.0.M2]......

Is it my configuration is wrong?
I hope to get your help.  Very grateful.  thank you very much.

**Comment by zhujiebing** [comment] 2019-07-26 07:45
> I can't reproduce the error using the `spring-boot-admin-sample-consul`

thanks! I reference spring-boot-admin-sample-consul and I have already solved this problem。
Now,I Full reference to spring-boot-admin-sample-consul. And I have another problem，when I add spring-boot-starter-mail jar, and i add mail configuration :
profiles:
active:
- secure
boot:
admin:
discovery:
ignored-services: consul

spring.mail.host: smtp.qq.com
spring.mail.username: 408989025@qq.com
spring.mail.password: 123456
spring.boot.admin.notify.mail.to: 1483864326@qq.com
spring.boot.admin.notify.mail.from: 408989025@qq.com

Can only receive admin server‘s Up and down email reminder， can not receive other services's
Up and down email reminder. And admin server throw an exception :

Couldn't retrieve status for Instance(id=b6c58bcdf63e, version=3, registration=Registration(name=consul-example......

java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 10000ms in 'map' (and no fallback has been configured)
at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.handleTimeout(FluxTimeout.java:288) [reactor-core-3.3.0.M2.jar:3.3.0.M2]
at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.doTimeout(FluxTimeout.java:273) [reactor-core-3.3.0.M2.jar:3.3.0.M2]......

Is it my configuration is wrong?
I hope to get your help. Very grateful. thank you very much.

**Comment by joshiste** [comment] 2019-07-26 09:17
I guess the SBA either server can't establish a connection to the client application or the application doesn't respond in time.

**Comment by zhujiebing** [comment] 2019-07-26 16:20
> I guess the SBA either server can't establish a connection to the client application or the application doesn't respond in time.

thanks.  This exception no longer appears now. 
When sba server start before  all  client application , and sba Console UI can show all client application is up status.,and consul UI has normal status.  But still can't receive notify mail.  all client application are depend  the spring-boot-admin-starter-client jar ,and  client application's yml  is   
cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true   

management:
  endpoints:
    web:
      exposure:
        include: '*'


and  my sba server project same as  spring-boot-admin-sample-consul. and i use spring-boot-starter-undertow.

I hope to get your help.  Thank you very much.  Trouble you.

**Comment by zhujiebing** [comment] 2019-07-27 15:04
> I guess the SBA either server can't establish a connection to the client application or the application doesn't respond in time.

Hi, i read Spring Boot Admin Reference Guide,  i refer to 4.5.3. Mail Notifications, Configure a JavaMailSender.   I did it.

@Configuration
public class AdminServerConfiguration {


    @Autowired
    private ApplicationContext applicationContext;

    public TemplateEngine mailNotifierTemplateEngine() {
        SpringResourceTemplateResolver resolver = new SpringResourceTemplateResolver();
        resolver.setApplicationContext(this.applicationContext);
        resolver.setTemplateMode(TemplateMode.HTML);
        resolver.setCharacterEncoding(StandardCharsets.UTF_8.name());

        SpringTemplateEngine templateEngine = new SpringTemplateEngine();
        templateEngine.addTemplateResolver(resolver);
        return templateEngine;
    }

    @Bean
    @ConfigurationProperties("spring.boot.admin.notify.mail")
    public Notifier notifier(JavaMailSender mailSender, InstanceRepository repository) {
        MailNotifier mailNotifier = new MailNotifier(mailSender, repository, mailNotifierTemplateEngine());
        mailNotifier.setIgnoreChanges(new String[]{});
        return mailNotifier;
    }
}



And now i can receive email alerts,     but i can only receive 'UNKNOWN to UP' email . When i stop client application,  can not receive Offline  status's email .        

notify:
        mail:
          enabled: true
          to: 1483864326@qq.com
          from: 408989025@qq.com
          ignore-changes: [""]

  mail:
    host: smtp.qq.com
    username: 408989025@qq.com
    password: qgytijtlmjyubjge


And this is my SBA server's  yml .    


And i want ask you another question ,   when sba server start before all client application ,  i start multiple client application at the same time,
 a warning appears :

 io.netty.handler.timeout.ReadTimeoutException: null

I hope to get your help. Thank you very much. Trouble you.

**Comment by joshiste** [comment] 2019-07-29 07:16
>io.netty.handler.timeout.ReadTimeoutException

means that the client application didn't responded in time.

>connection timed out: DESKTOP-6CSCCCJ.mshome.net/172.31.26.81:18000

means that the connection to the client application could not be established.

**Comment by zhujiebing** [comment] 2019-07-30 16:34
Thanks!  When i stop a client application, and status was DEREGISTERED, and no longer exists in Consul UI,   can I receive an email notification?   I know spring.boot.admin.notify.mail.ignore-changes default is  "UNKNOWN:UP" .   Can I receive alerts for all status changes?    .     Can you give me a Sample yml of mail ?     Thank you very much for your trouble.

**Comment by zhujiebing** [comment] 2019-07-30 16:35
> > io.netty.handler.timeout.ReadTimeoutException
> 
> means that the client application didn't responded in time.
> 
> > connection timed out: DESKTOP-6CSCCCJ.mshome.net/172.31.26.81:18000
> 
> means that the connection to the client application could not be established.

Thanks! When i stop a client application, and status was DEREGISTERED, and no longer exists in Consul UI, can I receive an email notification? I know spring.boot.admin.notify.mail.ignore-changes default is "UNKNOWN:UP" . Can I receive alerts for all status changes? . Can you give me a Sample yml of mail ? Thank you very much for your trouble.

**Comment by joshiste** [comment] 2019-07-30 17:19
> Thanks! When i stop a client application, then state becomes DEREGISTERED, and no longer exists in Consul UI, can I receive an email notification?

sounds like a duplicate of #1033

**Comment by zhujiebing** [comment] 2019-08-01 10:28
> > Thanks! When i stop a client application, then state becomes DEREGISTERED, and no longer exists in Consul UI, can I receive an email notification?
> 
> sounds like a duplicate of #1033

Thanks.

When sba send email , often appear such a warning log :  


Error while updating the snapshot with event InstanceRegisteredEvent(super=InstanceEvent(instance=f98c5b8be553, version=0, timestamp=2019-08-01T10:23:19.176Z, type=REGISTERED), registration=Registration(name=cvnavi-mss-gateway, managementUrl=http://DESKTOP-6CSCCCJ.mshome.net:18000/actuator, healthUrl=http://DESKTOP-6CSCCCJ.mshome.net:18000/actuator/health, serviceUrl=http://DESKTOP-6CSCCCJ.mshome.net:18000/, source=discovery))

java.lang.IllegalArgumentException: Event 0 must be greater or equal to 1
	at org.springframework.util.Assert.isTrue(Assert.java:136)
	at de.codecentric.boot.admin.server.domain.entities.Instance.apply(Instance.java:215)
	at de.codecentric.boot.admin.server.domain.entities.Instance.apply(Instance.java:209)
	at de.codecentric.boot.admin.server.domain.entities.SnapshottingInstanceRepository.lambda$updateSnapshot$5(SnapshottingInstanceRepository.java:100)
	at de.codecentric.boot.admin.server.domain.entities.SnapshottingInstanceRepository$$Lambda$956/2069229734.apply(Unknown Source)
	at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1877)


What is the reason? Can i ignore it?    

Thank you very much.

**Comment by zhujiebing** [comment] 2019-08-02 02:03
> > Thanks! When i stop a client application, then state becomes DEREGISTERED, and no longer exists in Consul UI, can I receive an email notification?
> 
> sounds like a duplicate of #1033

I want to ask you another question，  when i add a MyNotifier ,  if extends AbstractStatusChangeNotifier , it not work.  if extends AbstractEventNotifier,  doNotify is quite normal.

@Component
@Slf4j
public class MyNotifier extends AbstractStatusChangeNotifier {


    public MyNotifier(InstanceRepository repositpry) {
        super(repositpry);
    }


    @Override
    protected Mono<Void> doNotify(InstanceEvent event, Instance instance) {

thank you !

**Comment by joshiste** [comment] 2019-08-02 16:42
the important part (code from doNotify) is missing...

**Comment by zhujiebing** [comment] 2019-08-04 13:37
> the important part (code from doNotify) is missing...

Thanks, i have already solved this problem。

**Comment by zhujiebing** [comment] 2019-08-04 13:40
> > Thanks! When i stop a client application, then state becomes DEREGISTERED, and no longer exists in Consul UI, can I receive an email notification?
> 
> sounds like a duplicate of #1033

I saw your message #1033
“If you are using spring-boot-admin-client: There is an option that the services derigister on shutdown...”    

 I want to know how to do it, if i stop a client application ，and i can received a reminder.

**Comment by joshiste** [comment] 2019-08-05 19:46
As mentioned this is topic pf #1033
closing as duplicate

**Closed by joshiste** 2019-08-05 19:46 UTC
Labels: waiting-for-feedback
